// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interfaces.proto

package interfaces;

public final class Interfaces {
  private Interfaces() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface interface_info_askOrBuilder extends
      // @@protoc_insertion_point(interface_extends:interfaces.interface_info_ask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes uap_topic = 1;</code>
     *
     * <pre>
     *统一接入平台主题
     * </pre>
     */
    boolean hasUapTopic();
    /**
     * <code>optional bytes uap_topic = 1;</code>
     *
     * <pre>
     *统一接入平台主题
     * </pre>
     */
    com.google.protobuf.ByteString getUapTopic();

    /**
     * <code>optional bytes json_ask = 2;</code>
     *
     * <pre>
     *JSON字符串
     * </pre>
     */
    boolean hasJsonAsk();
    /**
     * <code>optional bytes json_ask = 2;</code>
     *
     * <pre>
     *JSON字符串
     * </pre>
     */
    com.google.protobuf.ByteString getJsonAsk();
  }
  /**
   * Protobuf type {@code interfaces.interface_info_ask}
   *
   * <pre>
   *接口信息 只做透传
   * </pre>
   */
  public static final class interface_info_ask extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:interfaces.interface_info_ask)
      interface_info_askOrBuilder {
    // Use interface_info_ask.newBuilder() to construct.
    private interface_info_ask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private interface_info_ask(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final interface_info_ask defaultInstance;
    public static interface_info_ask getDefaultInstance() {
      return defaultInstance;
    }

    public interface_info_ask getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private interface_info_ask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uapTopic_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              jsonAsk_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return interfaces.Interfaces.internal_static_interfaces_interface_info_ask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return interfaces.Interfaces.internal_static_interfaces_interface_info_ask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              interfaces.Interfaces.interface_info_ask.class, interfaces.Interfaces.interface_info_ask.Builder.class);
    }

    public static com.google.protobuf.Parser<interface_info_ask> PARSER =
        new com.google.protobuf.AbstractParser<interface_info_ask>() {
      public interface_info_ask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new interface_info_ask(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<interface_info_ask> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UAP_TOPIC_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString uapTopic_;
    /**
     * <code>optional bytes uap_topic = 1;</code>
     *
     * <pre>
     *统一接入平台主题
     * </pre>
     */
    public boolean hasUapTopic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes uap_topic = 1;</code>
     *
     * <pre>
     *统一接入平台主题
     * </pre>
     */
    public com.google.protobuf.ByteString getUapTopic() {
      return uapTopic_;
    }

    public static final int JSON_ASK_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString jsonAsk_;
    /**
     * <code>optional bytes json_ask = 2;</code>
     *
     * <pre>
     *JSON字符串
     * </pre>
     */
    public boolean hasJsonAsk() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes json_ask = 2;</code>
     *
     * <pre>
     *JSON字符串
     * </pre>
     */
    public com.google.protobuf.ByteString getJsonAsk() {
      return jsonAsk_;
    }

    private void initFields() {
      uapTopic_ = com.google.protobuf.ByteString.EMPTY;
      jsonAsk_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, uapTopic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, jsonAsk_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, uapTopic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, jsonAsk_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static interfaces.Interfaces.interface_info_ask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interfaces.Interfaces.interface_info_ask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interfaces.Interfaces.interface_info_ask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interfaces.Interfaces.interface_info_ask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interfaces.Interfaces.interface_info_ask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static interfaces.Interfaces.interface_info_ask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static interfaces.Interfaces.interface_info_ask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static interfaces.Interfaces.interface_info_ask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static interfaces.Interfaces.interface_info_ask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static interfaces.Interfaces.interface_info_ask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(interfaces.Interfaces.interface_info_ask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code interfaces.interface_info_ask}
     *
     * <pre>
     *接口信息 只做透传
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:interfaces.interface_info_ask)
        interfaces.Interfaces.interface_info_askOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return interfaces.Interfaces.internal_static_interfaces_interface_info_ask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return interfaces.Interfaces.internal_static_interfaces_interface_info_ask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                interfaces.Interfaces.interface_info_ask.class, interfaces.Interfaces.interface_info_ask.Builder.class);
      }

      // Construct using interfaces.Interfaces.interface_info_ask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uapTopic_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        jsonAsk_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return interfaces.Interfaces.internal_static_interfaces_interface_info_ask_descriptor;
      }

      public interfaces.Interfaces.interface_info_ask getDefaultInstanceForType() {
        return interfaces.Interfaces.interface_info_ask.getDefaultInstance();
      }

      public interfaces.Interfaces.interface_info_ask build() {
        interfaces.Interfaces.interface_info_ask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public interfaces.Interfaces.interface_info_ask buildPartial() {
        interfaces.Interfaces.interface_info_ask result = new interfaces.Interfaces.interface_info_ask(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uapTopic_ = uapTopic_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jsonAsk_ = jsonAsk_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof interfaces.Interfaces.interface_info_ask) {
          return mergeFrom((interfaces.Interfaces.interface_info_ask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(interfaces.Interfaces.interface_info_ask other) {
        if (other == interfaces.Interfaces.interface_info_ask.getDefaultInstance()) return this;
        if (other.hasUapTopic()) {
          setUapTopic(other.getUapTopic());
        }
        if (other.hasJsonAsk()) {
          setJsonAsk(other.getJsonAsk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        interfaces.Interfaces.interface_info_ask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (interfaces.Interfaces.interface_info_ask) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString uapTopic_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes uap_topic = 1;</code>
       *
       * <pre>
       *统一接入平台主题
       * </pre>
       */
      public boolean hasUapTopic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes uap_topic = 1;</code>
       *
       * <pre>
       *统一接入平台主题
       * </pre>
       */
      public com.google.protobuf.ByteString getUapTopic() {
        return uapTopic_;
      }
      /**
       * <code>optional bytes uap_topic = 1;</code>
       *
       * <pre>
       *统一接入平台主题
       * </pre>
       */
      public Builder setUapTopic(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uapTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes uap_topic = 1;</code>
       *
       * <pre>
       *统一接入平台主题
       * </pre>
       */
      public Builder clearUapTopic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uapTopic_ = getDefaultInstance().getUapTopic();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString jsonAsk_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes json_ask = 2;</code>
       *
       * <pre>
       *JSON字符串
       * </pre>
       */
      public boolean hasJsonAsk() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes json_ask = 2;</code>
       *
       * <pre>
       *JSON字符串
       * </pre>
       */
      public com.google.protobuf.ByteString getJsonAsk() {
        return jsonAsk_;
      }
      /**
       * <code>optional bytes json_ask = 2;</code>
       *
       * <pre>
       *JSON字符串
       * </pre>
       */
      public Builder setJsonAsk(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        jsonAsk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes json_ask = 2;</code>
       *
       * <pre>
       *JSON字符串
       * </pre>
       */
      public Builder clearJsonAsk() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jsonAsk_ = getDefaultInstance().getJsonAsk();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:interfaces.interface_info_ask)
    }

    static {
      defaultInstance = new interface_info_ask(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:interfaces.interface_info_ask)
  }

  public interface interface_info_ansOrBuilder extends
      // @@protoc_insertion_point(interface_extends:interfaces.interface_info_ans)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes json_ans = 1;</code>
     */
    boolean hasJsonAns();
    /**
     * <code>optional bytes json_ans = 1;</code>
     */
    com.google.protobuf.ByteString getJsonAns();

    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *内部使用错误代码(与业务无关)
     * </pre>
     */
    boolean hasError();
    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *内部使用错误代码(与业务无关)
     * </pre>
     */
    common.Common.errorinfo getError();
    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *内部使用错误代码(与业务无关)
     * </pre>
     */
    common.Common.errorinfoOrBuilder getErrorOrBuilder();
  }
  /**
   * Protobuf type {@code interfaces.interface_info_ans}
   */
  public static final class interface_info_ans extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:interfaces.interface_info_ans)
      interface_info_ansOrBuilder {
    // Use interface_info_ans.newBuilder() to construct.
    private interface_info_ans(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private interface_info_ans(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final interface_info_ans defaultInstance;
    public static interface_info_ans getDefaultInstance() {
      return defaultInstance;
    }

    public interface_info_ans getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private interface_info_ans(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              jsonAns_ = input.readBytes();
              break;
            }
            case 18: {
              common.Common.errorinfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = error_.toBuilder();
              }
              error_ = input.readMessage(common.Common.errorinfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(error_);
                error_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return interfaces.Interfaces.internal_static_interfaces_interface_info_ans_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return interfaces.Interfaces.internal_static_interfaces_interface_info_ans_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              interfaces.Interfaces.interface_info_ans.class, interfaces.Interfaces.interface_info_ans.Builder.class);
    }

    public static com.google.protobuf.Parser<interface_info_ans> PARSER =
        new com.google.protobuf.AbstractParser<interface_info_ans>() {
      public interface_info_ans parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new interface_info_ans(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<interface_info_ans> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int JSON_ANS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString jsonAns_;
    /**
     * <code>optional bytes json_ans = 1;</code>
     */
    public boolean hasJsonAns() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes json_ans = 1;</code>
     */
    public com.google.protobuf.ByteString getJsonAns() {
      return jsonAns_;
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private common.Common.errorinfo error_;
    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *内部使用错误代码(与业务无关)
     * </pre>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *内部使用错误代码(与业务无关)
     * </pre>
     */
    public common.Common.errorinfo getError() {
      return error_;
    }
    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *内部使用错误代码(与业务无关)
     * </pre>
     */
    public common.Common.errorinfoOrBuilder getErrorOrBuilder() {
      return error_;
    }

    private void initFields() {
      jsonAns_ = com.google.protobuf.ByteString.EMPTY;
      error_ = common.Common.errorinfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, jsonAns_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, error_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, jsonAns_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, error_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static interfaces.Interfaces.interface_info_ans parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interfaces.Interfaces.interface_info_ans parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interfaces.Interfaces.interface_info_ans parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interfaces.Interfaces.interface_info_ans parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interfaces.Interfaces.interface_info_ans parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static interfaces.Interfaces.interface_info_ans parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static interfaces.Interfaces.interface_info_ans parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static interfaces.Interfaces.interface_info_ans parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static interfaces.Interfaces.interface_info_ans parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static interfaces.Interfaces.interface_info_ans parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(interfaces.Interfaces.interface_info_ans prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code interfaces.interface_info_ans}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:interfaces.interface_info_ans)
        interfaces.Interfaces.interface_info_ansOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return interfaces.Interfaces.internal_static_interfaces_interface_info_ans_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return interfaces.Interfaces.internal_static_interfaces_interface_info_ans_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                interfaces.Interfaces.interface_info_ans.class, interfaces.Interfaces.interface_info_ans.Builder.class);
      }

      // Construct using interfaces.Interfaces.interface_info_ans.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getErrorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        jsonAns_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (errorBuilder_ == null) {
          error_ = common.Common.errorinfo.getDefaultInstance();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return interfaces.Interfaces.internal_static_interfaces_interface_info_ans_descriptor;
      }

      public interfaces.Interfaces.interface_info_ans getDefaultInstanceForType() {
        return interfaces.Interfaces.interface_info_ans.getDefaultInstance();
      }

      public interfaces.Interfaces.interface_info_ans build() {
        interfaces.Interfaces.interface_info_ans result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public interfaces.Interfaces.interface_info_ans buildPartial() {
        interfaces.Interfaces.interface_info_ans result = new interfaces.Interfaces.interface_info_ans(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jsonAns_ = jsonAns_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof interfaces.Interfaces.interface_info_ans) {
          return mergeFrom((interfaces.Interfaces.interface_info_ans)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(interfaces.Interfaces.interface_info_ans other) {
        if (other == interfaces.Interfaces.interface_info_ans.getDefaultInstance()) return this;
        if (other.hasJsonAns()) {
          setJsonAns(other.getJsonAns());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        interfaces.Interfaces.interface_info_ans parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (interfaces.Interfaces.interface_info_ans) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString jsonAns_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes json_ans = 1;</code>
       */
      public boolean hasJsonAns() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes json_ans = 1;</code>
       */
      public com.google.protobuf.ByteString getJsonAns() {
        return jsonAns_;
      }
      /**
       * <code>optional bytes json_ans = 1;</code>
       */
      public Builder setJsonAns(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jsonAns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes json_ans = 1;</code>
       */
      public Builder clearJsonAns() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jsonAns_ = getDefaultInstance().getJsonAns();
        onChanged();
        return this;
      }

      private common.Common.errorinfo error_ = common.Common.errorinfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.errorinfo, common.Common.errorinfo.Builder, common.Common.errorinfoOrBuilder> errorBuilder_;
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *内部使用错误代码(与业务无关)
       * </pre>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *内部使用错误代码(与业务无关)
       * </pre>
       */
      public common.Common.errorinfo getError() {
        if (errorBuilder_ == null) {
          return error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *内部使用错误代码(与业务无关)
       * </pre>
       */
      public Builder setError(common.Common.errorinfo value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *内部使用错误代码(与业务无关)
       * </pre>
       */
      public Builder setError(
          common.Common.errorinfo.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *内部使用错误代码(与业务无关)
       * </pre>
       */
      public Builder mergeError(common.Common.errorinfo value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              error_ != common.Common.errorinfo.getDefaultInstance()) {
            error_ =
              common.Common.errorinfo.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *内部使用错误代码(与业务无关)
       * </pre>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = common.Common.errorinfo.getDefaultInstance();
          onChanged();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *内部使用错误代码(与业务无关)
       * </pre>
       */
      public common.Common.errorinfo.Builder getErrorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *内部使用错误代码(与业务无关)
       * </pre>
       */
      public common.Common.errorinfoOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_;
        }
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *内部使用错误代码(与业务无关)
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.errorinfo, common.Common.errorinfo.Builder, common.Common.errorinfoOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              common.Common.errorinfo, common.Common.errorinfo.Builder, common.Common.errorinfoOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:interfaces.interface_info_ans)
    }

    static {
      defaultInstance = new interface_info_ans(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:interfaces.interface_info_ans)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_interfaces_interface_info_ask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_interfaces_interface_info_ask_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_interfaces_interface_info_ans_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_interfaces_interface_info_ans_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020interfaces.proto\022\ninterfaces\032\014common.p" +
      "roto\"9\n\022interface_info_ask\022\021\n\tuap_topic\030" +
      "\001 \001(\014\022\020\n\010json_ask\030\002 \001(\014\"H\n\022interface_inf" +
      "o_ans\022\020\n\010json_ans\030\001 \001(\014\022 \n\005error\030\002 \001(\0132\021" +
      ".common.errorinfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          common.Common.getDescriptor(),
        }, assigner);
    internal_static_interfaces_interface_info_ask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_interfaces_interface_info_ask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_interfaces_interface_info_ask_descriptor,
        new java.lang.String[] { "UapTopic", "JsonAsk", });
    internal_static_interfaces_interface_info_ans_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_interfaces_interface_info_ans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_interfaces_interface_info_ans_descriptor,
        new java.lang.String[] { "JsonAns", "Error", });
    common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
