// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UPS_login.proto

package UPS_login;

public final class UPSLogin {
  private UPSLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface login_infoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UPS_login.login_info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes user_image_url = 1;</code>
     *
     * <pre>
     *用户图像URL
     * </pre>
     */
    boolean hasUserImageUrl();
    /**
     * <code>optional bytes user_image_url = 1;</code>
     *
     * <pre>
     *用户图像URL
     * </pre>
     */
    com.google.protobuf.ByteString getUserImageUrl();

    /**
     * <code>optional bytes user_label1 = 2;</code>
     *
     * <pre>
     *用户标签1
     * </pre>
     */
    boolean hasUserLabel1();
    /**
     * <code>optional bytes user_label1 = 2;</code>
     *
     * <pre>
     *用户标签1
     * </pre>
     */
    com.google.protobuf.ByteString getUserLabel1();

    /**
     * <code>optional bytes user_label2 = 3;</code>
     *
     * <pre>
     *用户标签2
     * </pre>
     */
    boolean hasUserLabel2();
    /**
     * <code>optional bytes user_label2 = 3;</code>
     *
     * <pre>
     *用户标签2
     * </pre>
     */
    com.google.protobuf.ByteString getUserLabel2();

    /**
     * <code>optional bytes user_label3 = 4;</code>
     *
     * <pre>
     *用户标签3
     * </pre>
     */
    boolean hasUserLabel3();
    /**
     * <code>optional bytes user_label3 = 4;</code>
     *
     * <pre>
     *用户标签3
     * </pre>
     */
    com.google.protobuf.ByteString getUserLabel3();
  }
  /**
   * Protobuf type {@code UPS_login.login_info}
   *
   * <pre>
   * </pre>
   */
  public static final class login_info extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UPS_login.login_info)
      login_infoOrBuilder {
    // Use login_info.newBuilder() to construct.
    private login_info(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private login_info(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final login_info defaultInstance;
    public static login_info getDefaultInstance() {
      return defaultInstance;
    }

    public login_info getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private login_info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userImageUrl_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userLabel1_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userLabel2_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              userLabel3_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UPS_login.UPSLogin.internal_static_UPS_login_login_info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UPS_login.UPSLogin.internal_static_UPS_login_login_info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UPS_login.UPSLogin.login_info.class, UPS_login.UPSLogin.login_info.Builder.class);
    }

    public static com.google.protobuf.Parser<login_info> PARSER =
        new com.google.protobuf.AbstractParser<login_info>() {
      public login_info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new login_info(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<login_info> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_IMAGE_URL_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString userImageUrl_;
    /**
     * <code>optional bytes user_image_url = 1;</code>
     *
     * <pre>
     *用户图像URL
     * </pre>
     */
    public boolean hasUserImageUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes user_image_url = 1;</code>
     *
     * <pre>
     *用户图像URL
     * </pre>
     */
    public com.google.protobuf.ByteString getUserImageUrl() {
      return userImageUrl_;
    }

    public static final int USER_LABEL1_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString userLabel1_;
    /**
     * <code>optional bytes user_label1 = 2;</code>
     *
     * <pre>
     *用户标签1
     * </pre>
     */
    public boolean hasUserLabel1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes user_label1 = 2;</code>
     *
     * <pre>
     *用户标签1
     * </pre>
     */
    public com.google.protobuf.ByteString getUserLabel1() {
      return userLabel1_;
    }

    public static final int USER_LABEL2_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString userLabel2_;
    /**
     * <code>optional bytes user_label2 = 3;</code>
     *
     * <pre>
     *用户标签2
     * </pre>
     */
    public boolean hasUserLabel2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes user_label2 = 3;</code>
     *
     * <pre>
     *用户标签2
     * </pre>
     */
    public com.google.protobuf.ByteString getUserLabel2() {
      return userLabel2_;
    }

    public static final int USER_LABEL3_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString userLabel3_;
    /**
     * <code>optional bytes user_label3 = 4;</code>
     *
     * <pre>
     *用户标签3
     * </pre>
     */
    public boolean hasUserLabel3() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes user_label3 = 4;</code>
     *
     * <pre>
     *用户标签3
     * </pre>
     */
    public com.google.protobuf.ByteString getUserLabel3() {
      return userLabel3_;
    }

    private void initFields() {
      userImageUrl_ = com.google.protobuf.ByteString.EMPTY;
      userLabel1_ = com.google.protobuf.ByteString.EMPTY;
      userLabel2_ = com.google.protobuf.ByteString.EMPTY;
      userLabel3_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, userImageUrl_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, userLabel1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, userLabel2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, userLabel3_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, userImageUrl_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, userLabel1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, userLabel2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, userLabel3_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static UPS_login.UPSLogin.login_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UPS_login.UPSLogin.login_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UPS_login.UPSLogin.login_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UPS_login.UPSLogin.login_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static UPS_login.UPSLogin.login_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UPS_login.UPSLogin.login_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UPS_login.UPSLogin.login_info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UPS_login.login_info}
     *
     * <pre>
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UPS_login.login_info)
        UPS_login.UPSLogin.login_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UPS_login.UPSLogin.internal_static_UPS_login_login_info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UPS_login.UPSLogin.internal_static_UPS_login_login_info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UPS_login.UPSLogin.login_info.class, UPS_login.UPSLogin.login_info.Builder.class);
      }

      // Construct using UPS_login.UPSLogin.login_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userImageUrl_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        userLabel1_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        userLabel2_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        userLabel3_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UPS_login.UPSLogin.internal_static_UPS_login_login_info_descriptor;
      }

      public UPS_login.UPSLogin.login_info getDefaultInstanceForType() {
        return UPS_login.UPSLogin.login_info.getDefaultInstance();
      }

      public UPS_login.UPSLogin.login_info build() {
        UPS_login.UPSLogin.login_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UPS_login.UPSLogin.login_info buildPartial() {
        UPS_login.UPSLogin.login_info result = new UPS_login.UPSLogin.login_info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userImageUrl_ = userImageUrl_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userLabel1_ = userLabel1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userLabel2_ = userLabel2_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userLabel3_ = userLabel3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UPS_login.UPSLogin.login_info) {
          return mergeFrom((UPS_login.UPSLogin.login_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UPS_login.UPSLogin.login_info other) {
        if (other == UPS_login.UPSLogin.login_info.getDefaultInstance()) return this;
        if (other.hasUserImageUrl()) {
          setUserImageUrl(other.getUserImageUrl());
        }
        if (other.hasUserLabel1()) {
          setUserLabel1(other.getUserLabel1());
        }
        if (other.hasUserLabel2()) {
          setUserLabel2(other.getUserLabel2());
        }
        if (other.hasUserLabel3()) {
          setUserLabel3(other.getUserLabel3());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UPS_login.UPSLogin.login_info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UPS_login.UPSLogin.login_info) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString userImageUrl_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes user_image_url = 1;</code>
       *
       * <pre>
       *用户图像URL
       * </pre>
       */
      public boolean hasUserImageUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes user_image_url = 1;</code>
       *
       * <pre>
       *用户图像URL
       * </pre>
       */
      public com.google.protobuf.ByteString getUserImageUrl() {
        return userImageUrl_;
      }
      /**
       * <code>optional bytes user_image_url = 1;</code>
       *
       * <pre>
       *用户图像URL
       * </pre>
       */
      public Builder setUserImageUrl(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userImageUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes user_image_url = 1;</code>
       *
       * <pre>
       *用户图像URL
       * </pre>
       */
      public Builder clearUserImageUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userImageUrl_ = getDefaultInstance().getUserImageUrl();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString userLabel1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes user_label1 = 2;</code>
       *
       * <pre>
       *用户标签1
       * </pre>
       */
      public boolean hasUserLabel1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes user_label1 = 2;</code>
       *
       * <pre>
       *用户标签1
       * </pre>
       */
      public com.google.protobuf.ByteString getUserLabel1() {
        return userLabel1_;
      }
      /**
       * <code>optional bytes user_label1 = 2;</code>
       *
       * <pre>
       *用户标签1
       * </pre>
       */
      public Builder setUserLabel1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userLabel1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes user_label1 = 2;</code>
       *
       * <pre>
       *用户标签1
       * </pre>
       */
      public Builder clearUserLabel1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userLabel1_ = getDefaultInstance().getUserLabel1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString userLabel2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes user_label2 = 3;</code>
       *
       * <pre>
       *用户标签2
       * </pre>
       */
      public boolean hasUserLabel2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes user_label2 = 3;</code>
       *
       * <pre>
       *用户标签2
       * </pre>
       */
      public com.google.protobuf.ByteString getUserLabel2() {
        return userLabel2_;
      }
      /**
       * <code>optional bytes user_label2 = 3;</code>
       *
       * <pre>
       *用户标签2
       * </pre>
       */
      public Builder setUserLabel2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userLabel2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes user_label2 = 3;</code>
       *
       * <pre>
       *用户标签2
       * </pre>
       */
      public Builder clearUserLabel2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userLabel2_ = getDefaultInstance().getUserLabel2();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString userLabel3_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes user_label3 = 4;</code>
       *
       * <pre>
       *用户标签3
       * </pre>
       */
      public boolean hasUserLabel3() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes user_label3 = 4;</code>
       *
       * <pre>
       *用户标签3
       * </pre>
       */
      public com.google.protobuf.ByteString getUserLabel3() {
        return userLabel3_;
      }
      /**
       * <code>optional bytes user_label3 = 4;</code>
       *
       * <pre>
       *用户标签3
       * </pre>
       */
      public Builder setUserLabel3(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userLabel3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes user_label3 = 4;</code>
       *
       * <pre>
       *用户标签3
       * </pre>
       */
      public Builder clearUserLabel3() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userLabel3_ = getDefaultInstance().getUserLabel3();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UPS_login.login_info)
    }

    static {
      defaultInstance = new login_info(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UPS_login.login_info)
  }

  public interface login_info_askOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UPS_login.login_info_ask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 user_number = 1;</code>
     *
     * <pre>
     *用户个数
     * </pre>
     */
    boolean hasUserNumber();
    /**
     * <code>optional int32 user_number = 1;</code>
     *
     * <pre>
     *用户个数
     * </pre>
     */
    int getUserNumber();
  }
  /**
   * Protobuf type {@code UPS_login.login_info_ask}
   *
   * <pre>
   *登录页面用户标签查询
   * </pre>
   */
  public static final class login_info_ask extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UPS_login.login_info_ask)
      login_info_askOrBuilder {
    // Use login_info_ask.newBuilder() to construct.
    private login_info_ask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private login_info_ask(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final login_info_ask defaultInstance;
    public static login_info_ask getDefaultInstance() {
      return defaultInstance;
    }

    public login_info_ask getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private login_info_ask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UPS_login.UPSLogin.internal_static_UPS_login_login_info_ask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UPS_login.UPSLogin.internal_static_UPS_login_login_info_ask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UPS_login.UPSLogin.login_info_ask.class, UPS_login.UPSLogin.login_info_ask.Builder.class);
    }

    public static com.google.protobuf.Parser<login_info_ask> PARSER =
        new com.google.protobuf.AbstractParser<login_info_ask>() {
      public login_info_ask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new login_info_ask(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<login_info_ask> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_NUMBER_FIELD_NUMBER = 1;
    private int userNumber_;
    /**
     * <code>optional int32 user_number = 1;</code>
     *
     * <pre>
     *用户个数
     * </pre>
     */
    public boolean hasUserNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 user_number = 1;</code>
     *
     * <pre>
     *用户个数
     * </pre>
     */
    public int getUserNumber() {
      return userNumber_;
    }

    private void initFields() {
      userNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static UPS_login.UPSLogin.login_info_ask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UPS_login.UPSLogin.login_info_ask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info_ask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UPS_login.UPSLogin.login_info_ask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info_ask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UPS_login.UPSLogin.login_info_ask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info_ask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static UPS_login.UPSLogin.login_info_ask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info_ask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UPS_login.UPSLogin.login_info_ask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UPS_login.UPSLogin.login_info_ask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UPS_login.login_info_ask}
     *
     * <pre>
     *登录页面用户标签查询
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UPS_login.login_info_ask)
        UPS_login.UPSLogin.login_info_askOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UPS_login.UPSLogin.internal_static_UPS_login_login_info_ask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UPS_login.UPSLogin.internal_static_UPS_login_login_info_ask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UPS_login.UPSLogin.login_info_ask.class, UPS_login.UPSLogin.login_info_ask.Builder.class);
      }

      // Construct using UPS_login.UPSLogin.login_info_ask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UPS_login.UPSLogin.internal_static_UPS_login_login_info_ask_descriptor;
      }

      public UPS_login.UPSLogin.login_info_ask getDefaultInstanceForType() {
        return UPS_login.UPSLogin.login_info_ask.getDefaultInstance();
      }

      public UPS_login.UPSLogin.login_info_ask build() {
        UPS_login.UPSLogin.login_info_ask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UPS_login.UPSLogin.login_info_ask buildPartial() {
        UPS_login.UPSLogin.login_info_ask result = new UPS_login.UPSLogin.login_info_ask(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userNumber_ = userNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UPS_login.UPSLogin.login_info_ask) {
          return mergeFrom((UPS_login.UPSLogin.login_info_ask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UPS_login.UPSLogin.login_info_ask other) {
        if (other == UPS_login.UPSLogin.login_info_ask.getDefaultInstance()) return this;
        if (other.hasUserNumber()) {
          setUserNumber(other.getUserNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UPS_login.UPSLogin.login_info_ask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UPS_login.UPSLogin.login_info_ask) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userNumber_ ;
      /**
       * <code>optional int32 user_number = 1;</code>
       *
       * <pre>
       *用户个数
       * </pre>
       */
      public boolean hasUserNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 user_number = 1;</code>
       *
       * <pre>
       *用户个数
       * </pre>
       */
      public int getUserNumber() {
        return userNumber_;
      }
      /**
       * <code>optional int32 user_number = 1;</code>
       *
       * <pre>
       *用户个数
       * </pre>
       */
      public Builder setUserNumber(int value) {
        bitField0_ |= 0x00000001;
        userNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 user_number = 1;</code>
       *
       * <pre>
       *用户个数
       * </pre>
       */
      public Builder clearUserNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UPS_login.login_info_ask)
    }

    static {
      defaultInstance = new login_info_ask(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UPS_login.login_info_ask)
  }

  public interface login_info_ansOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UPS_login.login_info_ans)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .UPS_login.login_info info = 1;</code>
     *
     * <pre>
     *登录用户标签
     * </pre>
     */
    java.util.List<UPS_login.UPSLogin.login_info> 
        getInfoList();
    /**
     * <code>repeated .UPS_login.login_info info = 1;</code>
     *
     * <pre>
     *登录用户标签
     * </pre>
     */
    UPS_login.UPSLogin.login_info getInfo(int index);
    /**
     * <code>repeated .UPS_login.login_info info = 1;</code>
     *
     * <pre>
     *登录用户标签
     * </pre>
     */
    int getInfoCount();
    /**
     * <code>repeated .UPS_login.login_info info = 1;</code>
     *
     * <pre>
     *登录用户标签
     * </pre>
     */
    java.util.List<? extends UPS_login.UPSLogin.login_infoOrBuilder> 
        getInfoOrBuilderList();
    /**
     * <code>repeated .UPS_login.login_info info = 1;</code>
     *
     * <pre>
     *登录用户标签
     * </pre>
     */
    UPS_login.UPSLogin.login_infoOrBuilder getInfoOrBuilder(
        int index);

    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    boolean hasError();
    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    common.Common.errorinfo getError();
    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    common.Common.errorinfoOrBuilder getErrorOrBuilder();
  }
  /**
   * Protobuf type {@code UPS_login.login_info_ans}
   *
   * <pre>
   *登录页面用户标签List结果
   * </pre>
   */
  public static final class login_info_ans extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UPS_login.login_info_ans)
      login_info_ansOrBuilder {
    // Use login_info_ans.newBuilder() to construct.
    private login_info_ans(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private login_info_ans(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final login_info_ans defaultInstance;
    public static login_info_ans getDefaultInstance() {
      return defaultInstance;
    }

    public login_info_ans getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private login_info_ans(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                info_ = new java.util.ArrayList<UPS_login.UPSLogin.login_info>();
                mutable_bitField0_ |= 0x00000001;
              }
              info_.add(input.readMessage(UPS_login.UPSLogin.login_info.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              common.Common.errorinfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = error_.toBuilder();
              }
              error_ = input.readMessage(common.Common.errorinfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(error_);
                error_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          info_ = java.util.Collections.unmodifiableList(info_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UPS_login.UPSLogin.internal_static_UPS_login_login_info_ans_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UPS_login.UPSLogin.internal_static_UPS_login_login_info_ans_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UPS_login.UPSLogin.login_info_ans.class, UPS_login.UPSLogin.login_info_ans.Builder.class);
    }

    public static com.google.protobuf.Parser<login_info_ans> PARSER =
        new com.google.protobuf.AbstractParser<login_info_ans>() {
      public login_info_ans parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new login_info_ans(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<login_info_ans> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INFO_FIELD_NUMBER = 1;
    private java.util.List<UPS_login.UPSLogin.login_info> info_;
    /**
     * <code>repeated .UPS_login.login_info info = 1;</code>
     *
     * <pre>
     *登录用户标签
     * </pre>
     */
    public java.util.List<UPS_login.UPSLogin.login_info> getInfoList() {
      return info_;
    }
    /**
     * <code>repeated .UPS_login.login_info info = 1;</code>
     *
     * <pre>
     *登录用户标签
     * </pre>
     */
    public java.util.List<? extends UPS_login.UPSLogin.login_infoOrBuilder> 
        getInfoOrBuilderList() {
      return info_;
    }
    /**
     * <code>repeated .UPS_login.login_info info = 1;</code>
     *
     * <pre>
     *登录用户标签
     * </pre>
     */
    public int getInfoCount() {
      return info_.size();
    }
    /**
     * <code>repeated .UPS_login.login_info info = 1;</code>
     *
     * <pre>
     *登录用户标签
     * </pre>
     */
    public UPS_login.UPSLogin.login_info getInfo(int index) {
      return info_.get(index);
    }
    /**
     * <code>repeated .UPS_login.login_info info = 1;</code>
     *
     * <pre>
     *登录用户标签
     * </pre>
     */
    public UPS_login.UPSLogin.login_infoOrBuilder getInfoOrBuilder(
        int index) {
      return info_.get(index);
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private common.Common.errorinfo error_;
    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    public common.Common.errorinfo getError() {
      return error_;
    }
    /**
     * <code>optional .common.errorinfo error = 2;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    public common.Common.errorinfoOrBuilder getErrorOrBuilder() {
      return error_;
    }

    private void initFields() {
      info_ = java.util.Collections.emptyList();
      error_ = common.Common.errorinfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < info_.size(); i++) {
        output.writeMessage(1, info_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, error_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < info_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, error_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static UPS_login.UPSLogin.login_info_ans parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UPS_login.UPSLogin.login_info_ans parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info_ans parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UPS_login.UPSLogin.login_info_ans parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info_ans parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UPS_login.UPSLogin.login_info_ans parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info_ans parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static UPS_login.UPSLogin.login_info_ans parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static UPS_login.UPSLogin.login_info_ans parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UPS_login.UPSLogin.login_info_ans parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UPS_login.UPSLogin.login_info_ans prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UPS_login.login_info_ans}
     *
     * <pre>
     *登录页面用户标签List结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UPS_login.login_info_ans)
        UPS_login.UPSLogin.login_info_ansOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UPS_login.UPSLogin.internal_static_UPS_login_login_info_ans_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UPS_login.UPSLogin.internal_static_UPS_login_login_info_ans_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UPS_login.UPSLogin.login_info_ans.class, UPS_login.UPSLogin.login_info_ans.Builder.class);
      }

      // Construct using UPS_login.UPSLogin.login_info_ans.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
          getErrorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          infoBuilder_.clear();
        }
        if (errorBuilder_ == null) {
          error_ = common.Common.errorinfo.getDefaultInstance();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UPS_login.UPSLogin.internal_static_UPS_login_login_info_ans_descriptor;
      }

      public UPS_login.UPSLogin.login_info_ans getDefaultInstanceForType() {
        return UPS_login.UPSLogin.login_info_ans.getDefaultInstance();
      }

      public UPS_login.UPSLogin.login_info_ans build() {
        UPS_login.UPSLogin.login_info_ans result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UPS_login.UPSLogin.login_info_ans buildPartial() {
        UPS_login.UPSLogin.login_info_ans result = new UPS_login.UPSLogin.login_info_ans(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            info_ = java.util.Collections.unmodifiableList(info_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UPS_login.UPSLogin.login_info_ans) {
          return mergeFrom((UPS_login.UPSLogin.login_info_ans)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UPS_login.UPSLogin.login_info_ans other) {
        if (other == UPS_login.UPSLogin.login_info_ans.getDefaultInstance()) return this;
        if (infoBuilder_ == null) {
          if (!other.info_.isEmpty()) {
            if (info_.isEmpty()) {
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInfoIsMutable();
              info_.addAll(other.info_);
            }
            onChanged();
          }
        } else {
          if (!other.info_.isEmpty()) {
            if (infoBuilder_.isEmpty()) {
              infoBuilder_.dispose();
              infoBuilder_ = null;
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000001);
              infoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfoFieldBuilder() : null;
            } else {
              infoBuilder_.addAllMessages(other.info_);
            }
          }
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UPS_login.UPSLogin.login_info_ans parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UPS_login.UPSLogin.login_info_ans) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<UPS_login.UPSLogin.login_info> info_ =
        java.util.Collections.emptyList();
      private void ensureInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          info_ = new java.util.ArrayList<UPS_login.UPSLogin.login_info>(info_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          UPS_login.UPSLogin.login_info, UPS_login.UPSLogin.login_info.Builder, UPS_login.UPSLogin.login_infoOrBuilder> infoBuilder_;

      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public java.util.List<UPS_login.UPSLogin.login_info> getInfoList() {
        if (infoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(info_);
        } else {
          return infoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public int getInfoCount() {
        if (infoBuilder_ == null) {
          return info_.size();
        } else {
          return infoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public UPS_login.UPSLogin.login_info getInfo(int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);
        } else {
          return infoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public Builder setInfo(
          int index, UPS_login.UPSLogin.login_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.set(index, value);
          onChanged();
        } else {
          infoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public Builder setInfo(
          int index, UPS_login.UPSLogin.login_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.set(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public Builder addInfo(UPS_login.UPSLogin.login_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(value);
          onChanged();
        } else {
          infoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public Builder addInfo(
          int index, UPS_login.UPSLogin.login_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(index, value);
          onChanged();
        } else {
          infoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public Builder addInfo(
          UPS_login.UPSLogin.login_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public Builder addInfo(
          int index, UPS_login.UPSLogin.login_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public Builder addAllInfo(
          java.lang.Iterable<? extends UPS_login.UPSLogin.login_info> values) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, info_);
          onChanged();
        } else {
          infoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public Builder removeInfo(int index) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.remove(index);
          onChanged();
        } else {
          infoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public UPS_login.UPSLogin.login_info.Builder getInfoBuilder(
          int index) {
        return getInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public UPS_login.UPSLogin.login_infoOrBuilder getInfoOrBuilder(
          int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);  } else {
          return infoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public java.util.List<? extends UPS_login.UPSLogin.login_infoOrBuilder> 
           getInfoOrBuilderList() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(info_);
        }
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public UPS_login.UPSLogin.login_info.Builder addInfoBuilder() {
        return getInfoFieldBuilder().addBuilder(
            UPS_login.UPSLogin.login_info.getDefaultInstance());
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public UPS_login.UPSLogin.login_info.Builder addInfoBuilder(
          int index) {
        return getInfoFieldBuilder().addBuilder(
            index, UPS_login.UPSLogin.login_info.getDefaultInstance());
      }
      /**
       * <code>repeated .UPS_login.login_info info = 1;</code>
       *
       * <pre>
       *登录用户标签
       * </pre>
       */
      public java.util.List<UPS_login.UPSLogin.login_info.Builder> 
           getInfoBuilderList() {
        return getInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          UPS_login.UPSLogin.login_info, UPS_login.UPSLogin.login_info.Builder, UPS_login.UPSLogin.login_infoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              UPS_login.UPSLogin.login_info, UPS_login.UPSLogin.login_info.Builder, UPS_login.UPSLogin.login_infoOrBuilder>(
                  info_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      private common.Common.errorinfo error_ = common.Common.errorinfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.errorinfo, common.Common.errorinfo.Builder, common.Common.errorinfoOrBuilder> errorBuilder_;
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public common.Common.errorinfo getError() {
        if (errorBuilder_ == null) {
          return error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public Builder setError(common.Common.errorinfo value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public Builder setError(
          common.Common.errorinfo.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public Builder mergeError(common.Common.errorinfo value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              error_ != common.Common.errorinfo.getDefaultInstance()) {
            error_ =
              common.Common.errorinfo.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = common.Common.errorinfo.getDefaultInstance();
          onChanged();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public common.Common.errorinfo.Builder getErrorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public common.Common.errorinfoOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_;
        }
      }
      /**
       * <code>optional .common.errorinfo error = 2;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.errorinfo, common.Common.errorinfo.Builder, common.Common.errorinfoOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              common.Common.errorinfo, common.Common.errorinfo.Builder, common.Common.errorinfoOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:UPS_login.login_info_ans)
    }

    static {
      defaultInstance = new login_info_ans(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UPS_login.login_info_ans)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UPS_login_login_info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UPS_login_login_info_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UPS_login_login_info_ask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UPS_login_login_info_ask_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UPS_login_login_info_ans_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UPS_login_login_info_ans_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017UPS_login.proto\022\tUPS_login\032\014common.pro" +
      "to\"c\n\nlogin_info\022\026\n\016user_image_url\030\001 \001(\014" +
      "\022\023\n\013user_label1\030\002 \001(\014\022\023\n\013user_label2\030\003 \001" +
      "(\014\022\023\n\013user_label3\030\004 \001(\014\"%\n\016login_info_as" +
      "k\022\023\n\013user_number\030\001 \001(\005\"W\n\016login_info_ans" +
      "\022#\n\004info\030\001 \003(\0132\025.UPS_login.login_info\022 \n" +
      "\005error\030\002 \001(\0132\021.common.errorinfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          common.Common.getDescriptor(),
        }, assigner);
    internal_static_UPS_login_login_info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UPS_login_login_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UPS_login_login_info_descriptor,
        new java.lang.String[] { "UserImageUrl", "UserLabel1", "UserLabel2", "UserLabel3", });
    internal_static_UPS_login_login_info_ask_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UPS_login_login_info_ask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UPS_login_login_info_ask_descriptor,
        new java.lang.String[] { "UserNumber", });
    internal_static_UPS_login_login_info_ans_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UPS_login_login_info_ans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UPS_login_login_info_ans_descriptor,
        new java.lang.String[] { "Info", "Error", });
    common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
