// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QDP_main_frame.proto

package QDP_main_frame;

public final class QDPMainFrame {
  private QDPMainFrame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code QDP_main_frame.other_platform}
   *
   * <pre>
   *第三方平台的宏定义
   * </pre>
   */
  public enum other_platform
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>unknown_platform = 0;</code>
     *
     * <pre>
     *未知平台
     * </pre>
     */
    unknown_platform(0, 0),
    /**
     * <code>Credit_sesame = 1;</code>
     *
     * <pre>
     *芝麻信用
     * </pre>
     */
    Credit_sesame(1, 1),
    /**
     * <code>fraud_metrix = 2;</code>
     *
     * <pre>
     *同盾
     * </pre>
     */
    fraud_metrix(2, 2),
    /**
     * <code>AnRong_Platform = 3;</code>
     *
     * <pre>
     *安融
     * </pre>
     */
    AnRong_Platform(3, 3),
    ;

    /**
     * <code>unknown_platform = 0;</code>
     *
     * <pre>
     *未知平台
     * </pre>
     */
    public static final int unknown_platform_VALUE = 0;
    /**
     * <code>Credit_sesame = 1;</code>
     *
     * <pre>
     *芝麻信用
     * </pre>
     */
    public static final int Credit_sesame_VALUE = 1;
    /**
     * <code>fraud_metrix = 2;</code>
     *
     * <pre>
     *同盾
     * </pre>
     */
    public static final int fraud_metrix_VALUE = 2;
    /**
     * <code>AnRong_Platform = 3;</code>
     *
     * <pre>
     *安融
     * </pre>
     */
    public static final int AnRong_Platform_VALUE = 3;


    public final int getNumber() { return value; }

    public static other_platform valueOf(int value) {
      switch (value) {
        case 0: return unknown_platform;
        case 1: return Credit_sesame;
        case 2: return fraud_metrix;
        case 3: return AnRong_Platform;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<other_platform>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<other_platform>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<other_platform>() {
            public other_platform findValueByNumber(int number) {
              return other_platform.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return QDP_main_frame.QDPMainFrame.getDescriptor().getEnumTypes().get(0);
    }

    private static final other_platform[] VALUES = values();

    public static other_platform valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private other_platform(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:QDP_main_frame.other_platform)
  }

  public interface user_verification_askOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QDP_main_frame.user_verification_ask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
     */
    boolean hasInfo();
    /**
     * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
     */
    QDP_basic_info.QDPBasicInfo.user_basic_info getInfo();
    /**
     * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
     */
    QDP_basic_info.QDPBasicInfo.user_basic_infoOrBuilder getInfoOrBuilder();

    /**
     * <code>optional .QDP_main_frame.other_platform platform_type = 2;</code>
     *
     * <pre>
     *所属平台
     * </pre>
     */
    boolean hasPlatformType();
    /**
     * <code>optional .QDP_main_frame.other_platform platform_type = 2;</code>
     *
     * <pre>
     *所属平台
     * </pre>
     */
    QDP_main_frame.QDPMainFrame.other_platform getPlatformType();

    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     *指定发送的主题
     * </pre>
     */
    boolean hasAskHeader();
    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     *指定发送的主题
     * </pre>
     */
    common.Common.common_ask_header getAskHeader();
    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     *指定发送的主题
     * </pre>
     */
    common.Common.common_ask_headerOrBuilder getAskHeaderOrBuilder();

    /**
     * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
     *
     * <pre>
     *服务管理
     * </pre>
     */
    boolean hasServiceManager();
    /**
     * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
     *
     * <pre>
     *服务管理
     * </pre>
     */
    QDP_basic_info.QDPBasicInfo.control_service getServiceManager();
    /**
     * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
     *
     * <pre>
     *服务管理
     * </pre>
     */
    QDP_basic_info.QDPBasicInfo.control_serviceOrBuilder getServiceManagerOrBuilder();

    /**
     * <code>optional int32 query_type = 5 [default = 0];</code>
     *
     * <pre>
     *访问量化数据平台查询类型 0：量化平台访问第三方获取数据。 1：量化平台从数据库获取最新一条记录返回。 2：县访问数据库，如果查不到记录则访问第三方
     * </pre>
     */
    boolean hasQueryType();
    /**
     * <code>optional int32 query_type = 5 [default = 0];</code>
     *
     * <pre>
     *访问量化数据平台查询类型 0：量化平台访问第三方获取数据。 1：量化平台从数据库获取最新一条记录返回。 2：县访问数据库，如果查不到记录则访问第三方
     * </pre>
     */
    int getQueryType();
  }
  /**
   * Protobuf type {@code QDP_main_frame.user_verification_ask}
   *
   * <pre>
   *用户验证
   * </pre>
   */
  public static final class user_verification_ask extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:QDP_main_frame.user_verification_ask)
      user_verification_askOrBuilder {
    // Use user_verification_ask.newBuilder() to construct.
    private user_verification_ask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private user_verification_ask(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final user_verification_ask defaultInstance;
    public static user_verification_ask getDefaultInstance() {
      return defaultInstance;
    }

    public user_verification_ask getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private user_verification_ask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              QDP_basic_info.QDPBasicInfo.user_basic_info.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(QDP_basic_info.QDPBasicInfo.user_basic_info.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              QDP_main_frame.QDPMainFrame.other_platform value = QDP_main_frame.QDPMainFrame.other_platform.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                platformType_ = value;
              }
              break;
            }
            case 26: {
              common.Common.common_ask_header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = askHeader_.toBuilder();
              }
              askHeader_ = input.readMessage(common.Common.common_ask_header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(askHeader_);
                askHeader_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              QDP_basic_info.QDPBasicInfo.control_service.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = serviceManager_.toBuilder();
              }
              serviceManager_ = input.readMessage(QDP_basic_info.QDPBasicInfo.control_service.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serviceManager_);
                serviceManager_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              queryType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QDP_main_frame.QDPMainFrame.internal_static_QDP_main_frame_user_verification_ask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QDP_main_frame.QDPMainFrame.internal_static_QDP_main_frame_user_verification_ask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QDP_main_frame.QDPMainFrame.user_verification_ask.class, QDP_main_frame.QDPMainFrame.user_verification_ask.Builder.class);
    }

    public static com.google.protobuf.Parser<user_verification_ask> PARSER =
        new com.google.protobuf.AbstractParser<user_verification_ask>() {
      public user_verification_ask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new user_verification_ask(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<user_verification_ask> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INFO_FIELD_NUMBER = 1;
    private QDP_basic_info.QDPBasicInfo.user_basic_info info_;
    /**
     * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
     */
    public QDP_basic_info.QDPBasicInfo.user_basic_info getInfo() {
      return info_;
    }
    /**
     * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
     */
    public QDP_basic_info.QDPBasicInfo.user_basic_infoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    public static final int PLATFORM_TYPE_FIELD_NUMBER = 2;
    private QDP_main_frame.QDPMainFrame.other_platform platformType_;
    /**
     * <code>optional .QDP_main_frame.other_platform platform_type = 2;</code>
     *
     * <pre>
     *所属平台
     * </pre>
     */
    public boolean hasPlatformType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .QDP_main_frame.other_platform platform_type = 2;</code>
     *
     * <pre>
     *所属平台
     * </pre>
     */
    public QDP_main_frame.QDPMainFrame.other_platform getPlatformType() {
      return platformType_;
    }

    public static final int ASK_HEADER_FIELD_NUMBER = 3;
    private common.Common.common_ask_header askHeader_;
    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     *指定发送的主题
     * </pre>
     */
    public boolean hasAskHeader() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     *指定发送的主题
     * </pre>
     */
    public common.Common.common_ask_header getAskHeader() {
      return askHeader_;
    }
    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     *指定发送的主题
     * </pre>
     */
    public common.Common.common_ask_headerOrBuilder getAskHeaderOrBuilder() {
      return askHeader_;
    }

    public static final int SERVICE_MANAGER_FIELD_NUMBER = 4;
    private QDP_basic_info.QDPBasicInfo.control_service serviceManager_;
    /**
     * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
     *
     * <pre>
     *服务管理
     * </pre>
     */
    public boolean hasServiceManager() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
     *
     * <pre>
     *服务管理
     * </pre>
     */
    public QDP_basic_info.QDPBasicInfo.control_service getServiceManager() {
      return serviceManager_;
    }
    /**
     * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
     *
     * <pre>
     *服务管理
     * </pre>
     */
    public QDP_basic_info.QDPBasicInfo.control_serviceOrBuilder getServiceManagerOrBuilder() {
      return serviceManager_;
    }

    public static final int QUERY_TYPE_FIELD_NUMBER = 5;
    private int queryType_;
    /**
     * <code>optional int32 query_type = 5 [default = 0];</code>
     *
     * <pre>
     *访问量化数据平台查询类型 0：量化平台访问第三方获取数据。 1：量化平台从数据库获取最新一条记录返回。 2：县访问数据库，如果查不到记录则访问第三方
     * </pre>
     */
    public boolean hasQueryType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 query_type = 5 [default = 0];</code>
     *
     * <pre>
     *访问量化数据平台查询类型 0：量化平台访问第三方获取数据。 1：量化平台从数据库获取最新一条记录返回。 2：县访问数据库，如果查不到记录则访问第三方
     * </pre>
     */
    public int getQueryType() {
      return queryType_;
    }

    private void initFields() {
      info_ = QDP_basic_info.QDPBasicInfo.user_basic_info.getDefaultInstance();
      platformType_ = QDP_main_frame.QDPMainFrame.other_platform.unknown_platform;
      askHeader_ = common.Common.common_ask_header.getDefaultInstance();
      serviceManager_ = QDP_basic_info.QDPBasicInfo.control_service.getDefaultInstance();
      queryType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, info_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, platformType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, askHeader_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, serviceManager_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, queryType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, platformType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, askHeader_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, serviceManager_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, queryType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static QDP_main_frame.QDPMainFrame.user_verification_ask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QDP_main_frame.QDPMainFrame.user_verification_ask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QDP_main_frame.user_verification_ask}
     *
     * <pre>
     *用户验证
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QDP_main_frame.user_verification_ask)
        QDP_main_frame.QDPMainFrame.user_verification_askOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QDP_main_frame.QDPMainFrame.internal_static_QDP_main_frame_user_verification_ask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QDP_main_frame.QDPMainFrame.internal_static_QDP_main_frame_user_verification_ask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QDP_main_frame.QDPMainFrame.user_verification_ask.class, QDP_main_frame.QDPMainFrame.user_verification_ask.Builder.class);
      }

      // Construct using QDP_main_frame.QDPMainFrame.user_verification_ask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
          getAskHeaderFieldBuilder();
          getServiceManagerFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = QDP_basic_info.QDPBasicInfo.user_basic_info.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        platformType_ = QDP_main_frame.QDPMainFrame.other_platform.unknown_platform;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (askHeaderBuilder_ == null) {
          askHeader_ = common.Common.common_ask_header.getDefaultInstance();
        } else {
          askHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (serviceManagerBuilder_ == null) {
          serviceManager_ = QDP_basic_info.QDPBasicInfo.control_service.getDefaultInstance();
        } else {
          serviceManagerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        queryType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QDP_main_frame.QDPMainFrame.internal_static_QDP_main_frame_user_verification_ask_descriptor;
      }

      public QDP_main_frame.QDPMainFrame.user_verification_ask getDefaultInstanceForType() {
        return QDP_main_frame.QDPMainFrame.user_verification_ask.getDefaultInstance();
      }

      public QDP_main_frame.QDPMainFrame.user_verification_ask build() {
        QDP_main_frame.QDPMainFrame.user_verification_ask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public QDP_main_frame.QDPMainFrame.user_verification_ask buildPartial() {
        QDP_main_frame.QDPMainFrame.user_verification_ask result = new QDP_main_frame.QDPMainFrame.user_verification_ask(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.platformType_ = platformType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (askHeaderBuilder_ == null) {
          result.askHeader_ = askHeader_;
        } else {
          result.askHeader_ = askHeaderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (serviceManagerBuilder_ == null) {
          result.serviceManager_ = serviceManager_;
        } else {
          result.serviceManager_ = serviceManagerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.queryType_ = queryType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QDP_main_frame.QDPMainFrame.user_verification_ask) {
          return mergeFrom((QDP_main_frame.QDPMainFrame.user_verification_ask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QDP_main_frame.QDPMainFrame.user_verification_ask other) {
        if (other == QDP_main_frame.QDPMainFrame.user_verification_ask.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (other.hasPlatformType()) {
          setPlatformType(other.getPlatformType());
        }
        if (other.hasAskHeader()) {
          mergeAskHeader(other.getAskHeader());
        }
        if (other.hasServiceManager()) {
          mergeServiceManager(other.getServiceManager());
        }
        if (other.hasQueryType()) {
          setQueryType(other.getQueryType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QDP_main_frame.QDPMainFrame.user_verification_ask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QDP_main_frame.QDPMainFrame.user_verification_ask) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private QDP_basic_info.QDPBasicInfo.user_basic_info info_ = QDP_basic_info.QDPBasicInfo.user_basic_info.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          QDP_basic_info.QDPBasicInfo.user_basic_info, QDP_basic_info.QDPBasicInfo.user_basic_info.Builder, QDP_basic_info.QDPBasicInfo.user_basic_infoOrBuilder> infoBuilder_;
      /**
       * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
       */
      public QDP_basic_info.QDPBasicInfo.user_basic_info getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
       */
      public Builder setInfo(QDP_basic_info.QDPBasicInfo.user_basic_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
       */
      public Builder setInfo(
          QDP_basic_info.QDPBasicInfo.user_basic_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
       */
      public Builder mergeInfo(QDP_basic_info.QDPBasicInfo.user_basic_info value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              info_ != QDP_basic_info.QDPBasicInfo.user_basic_info.getDefaultInstance()) {
            info_ =
              QDP_basic_info.QDPBasicInfo.user_basic_info.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = QDP_basic_info.QDPBasicInfo.user_basic_info.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
       */
      public QDP_basic_info.QDPBasicInfo.user_basic_info.Builder getInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
       */
      public QDP_basic_info.QDPBasicInfo.user_basic_infoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>optional .QDP_basic_info.user_basic_info info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          QDP_basic_info.QDPBasicInfo.user_basic_info, QDP_basic_info.QDPBasicInfo.user_basic_info.Builder, QDP_basic_info.QDPBasicInfo.user_basic_infoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              QDP_basic_info.QDPBasicInfo.user_basic_info, QDP_basic_info.QDPBasicInfo.user_basic_info.Builder, QDP_basic_info.QDPBasicInfo.user_basic_infoOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      private QDP_main_frame.QDPMainFrame.other_platform platformType_ = QDP_main_frame.QDPMainFrame.other_platform.unknown_platform;
      /**
       * <code>optional .QDP_main_frame.other_platform platform_type = 2;</code>
       *
       * <pre>
       *所属平台
       * </pre>
       */
      public boolean hasPlatformType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .QDP_main_frame.other_platform platform_type = 2;</code>
       *
       * <pre>
       *所属平台
       * </pre>
       */
      public QDP_main_frame.QDPMainFrame.other_platform getPlatformType() {
        return platformType_;
      }
      /**
       * <code>optional .QDP_main_frame.other_platform platform_type = 2;</code>
       *
       * <pre>
       *所属平台
       * </pre>
       */
      public Builder setPlatformType(QDP_main_frame.QDPMainFrame.other_platform value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        platformType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .QDP_main_frame.other_platform platform_type = 2;</code>
       *
       * <pre>
       *所属平台
       * </pre>
       */
      public Builder clearPlatformType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        platformType_ = QDP_main_frame.QDPMainFrame.other_platform.unknown_platform;
        onChanged();
        return this;
      }

      private common.Common.common_ask_header askHeader_ = common.Common.common_ask_header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.common_ask_header, common.Common.common_ask_header.Builder, common.Common.common_ask_headerOrBuilder> askHeaderBuilder_;
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       *指定发送的主题
       * </pre>
       */
      public boolean hasAskHeader() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       *指定发送的主题
       * </pre>
       */
      public common.Common.common_ask_header getAskHeader() {
        if (askHeaderBuilder_ == null) {
          return askHeader_;
        } else {
          return askHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       *指定发送的主题
       * </pre>
       */
      public Builder setAskHeader(common.Common.common_ask_header value) {
        if (askHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          askHeader_ = value;
          onChanged();
        } else {
          askHeaderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       *指定发送的主题
       * </pre>
       */
      public Builder setAskHeader(
          common.Common.common_ask_header.Builder builderForValue) {
        if (askHeaderBuilder_ == null) {
          askHeader_ = builderForValue.build();
          onChanged();
        } else {
          askHeaderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       *指定发送的主题
       * </pre>
       */
      public Builder mergeAskHeader(common.Common.common_ask_header value) {
        if (askHeaderBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              askHeader_ != common.Common.common_ask_header.getDefaultInstance()) {
            askHeader_ =
              common.Common.common_ask_header.newBuilder(askHeader_).mergeFrom(value).buildPartial();
          } else {
            askHeader_ = value;
          }
          onChanged();
        } else {
          askHeaderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       *指定发送的主题
       * </pre>
       */
      public Builder clearAskHeader() {
        if (askHeaderBuilder_ == null) {
          askHeader_ = common.Common.common_ask_header.getDefaultInstance();
          onChanged();
        } else {
          askHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       *指定发送的主题
       * </pre>
       */
      public common.Common.common_ask_header.Builder getAskHeaderBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAskHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       *指定发送的主题
       * </pre>
       */
      public common.Common.common_ask_headerOrBuilder getAskHeaderOrBuilder() {
        if (askHeaderBuilder_ != null) {
          return askHeaderBuilder_.getMessageOrBuilder();
        } else {
          return askHeader_;
        }
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       *指定发送的主题
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.common_ask_header, common.Common.common_ask_header.Builder, common.Common.common_ask_headerOrBuilder> 
          getAskHeaderFieldBuilder() {
        if (askHeaderBuilder_ == null) {
          askHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              common.Common.common_ask_header, common.Common.common_ask_header.Builder, common.Common.common_ask_headerOrBuilder>(
                  getAskHeader(),
                  getParentForChildren(),
                  isClean());
          askHeader_ = null;
        }
        return askHeaderBuilder_;
      }

      private QDP_basic_info.QDPBasicInfo.control_service serviceManager_ = QDP_basic_info.QDPBasicInfo.control_service.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          QDP_basic_info.QDPBasicInfo.control_service, QDP_basic_info.QDPBasicInfo.control_service.Builder, QDP_basic_info.QDPBasicInfo.control_serviceOrBuilder> serviceManagerBuilder_;
      /**
       * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
       *
       * <pre>
       *服务管理
       * </pre>
       */
      public boolean hasServiceManager() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
       *
       * <pre>
       *服务管理
       * </pre>
       */
      public QDP_basic_info.QDPBasicInfo.control_service getServiceManager() {
        if (serviceManagerBuilder_ == null) {
          return serviceManager_;
        } else {
          return serviceManagerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
       *
       * <pre>
       *服务管理
       * </pre>
       */
      public Builder setServiceManager(QDP_basic_info.QDPBasicInfo.control_service value) {
        if (serviceManagerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serviceManager_ = value;
          onChanged();
        } else {
          serviceManagerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
       *
       * <pre>
       *服务管理
       * </pre>
       */
      public Builder setServiceManager(
          QDP_basic_info.QDPBasicInfo.control_service.Builder builderForValue) {
        if (serviceManagerBuilder_ == null) {
          serviceManager_ = builderForValue.build();
          onChanged();
        } else {
          serviceManagerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
       *
       * <pre>
       *服务管理
       * </pre>
       */
      public Builder mergeServiceManager(QDP_basic_info.QDPBasicInfo.control_service value) {
        if (serviceManagerBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              serviceManager_ != QDP_basic_info.QDPBasicInfo.control_service.getDefaultInstance()) {
            serviceManager_ =
              QDP_basic_info.QDPBasicInfo.control_service.newBuilder(serviceManager_).mergeFrom(value).buildPartial();
          } else {
            serviceManager_ = value;
          }
          onChanged();
        } else {
          serviceManagerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
       *
       * <pre>
       *服务管理
       * </pre>
       */
      public Builder clearServiceManager() {
        if (serviceManagerBuilder_ == null) {
          serviceManager_ = QDP_basic_info.QDPBasicInfo.control_service.getDefaultInstance();
          onChanged();
        } else {
          serviceManagerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
       *
       * <pre>
       *服务管理
       * </pre>
       */
      public QDP_basic_info.QDPBasicInfo.control_service.Builder getServiceManagerBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getServiceManagerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
       *
       * <pre>
       *服务管理
       * </pre>
       */
      public QDP_basic_info.QDPBasicInfo.control_serviceOrBuilder getServiceManagerOrBuilder() {
        if (serviceManagerBuilder_ != null) {
          return serviceManagerBuilder_.getMessageOrBuilder();
        } else {
          return serviceManager_;
        }
      }
      /**
       * <code>optional .QDP_basic_info.control_service service_manager = 4;</code>
       *
       * <pre>
       *服务管理
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          QDP_basic_info.QDPBasicInfo.control_service, QDP_basic_info.QDPBasicInfo.control_service.Builder, QDP_basic_info.QDPBasicInfo.control_serviceOrBuilder> 
          getServiceManagerFieldBuilder() {
        if (serviceManagerBuilder_ == null) {
          serviceManagerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              QDP_basic_info.QDPBasicInfo.control_service, QDP_basic_info.QDPBasicInfo.control_service.Builder, QDP_basic_info.QDPBasicInfo.control_serviceOrBuilder>(
                  getServiceManager(),
                  getParentForChildren(),
                  isClean());
          serviceManager_ = null;
        }
        return serviceManagerBuilder_;
      }

      private int queryType_ ;
      /**
       * <code>optional int32 query_type = 5 [default = 0];</code>
       *
       * <pre>
       *访问量化数据平台查询类型 0：量化平台访问第三方获取数据。 1：量化平台从数据库获取最新一条记录返回。 2：县访问数据库，如果查不到记录则访问第三方
       * </pre>
       */
      public boolean hasQueryType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 query_type = 5 [default = 0];</code>
       *
       * <pre>
       *访问量化数据平台查询类型 0：量化平台访问第三方获取数据。 1：量化平台从数据库获取最新一条记录返回。 2：县访问数据库，如果查不到记录则访问第三方
       * </pre>
       */
      public int getQueryType() {
        return queryType_;
      }
      /**
       * <code>optional int32 query_type = 5 [default = 0];</code>
       *
       * <pre>
       *访问量化数据平台查询类型 0：量化平台访问第三方获取数据。 1：量化平台从数据库获取最新一条记录返回。 2：县访问数据库，如果查不到记录则访问第三方
       * </pre>
       */
      public Builder setQueryType(int value) {
        bitField0_ |= 0x00000010;
        queryType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 query_type = 5 [default = 0];</code>
       *
       * <pre>
       *访问量化数据平台查询类型 0：量化平台访问第三方获取数据。 1：量化平台从数据库获取最新一条记录返回。 2：县访问数据库，如果查不到记录则访问第三方
       * </pre>
       */
      public Builder clearQueryType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        queryType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:QDP_main_frame.user_verification_ask)
    }

    static {
      defaultInstance = new user_verification_ask(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:QDP_main_frame.user_verification_ask)
  }

  public interface user_verification_ansOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QDP_main_frame.user_verification_ans)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .QDP_main_frame.other_platform platform_type = 1;</code>
     *
     * <pre>
     *所属平台
     * </pre>
     */
    boolean hasPlatformType();
    /**
     * <code>optional .QDP_main_frame.other_platform platform_type = 1;</code>
     *
     * <pre>
     *所属平台
     * </pre>
     */
    QDP_main_frame.QDPMainFrame.other_platform getPlatformType();

    /**
     * <code>optional bytes json_ans = 2;</code>
     */
    boolean hasJsonAns();
    /**
     * <code>optional bytes json_ans = 2;</code>
     */
    com.google.protobuf.ByteString getJsonAns();

    /**
     * <code>optional .common.errorinfo error = 3;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    boolean hasError();
    /**
     * <code>optional .common.errorinfo error = 3;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    common.Common.errorinfo getError();
    /**
     * <code>optional .common.errorinfo error = 3;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    common.Common.errorinfoOrBuilder getErrorOrBuilder();
  }
  /**
   * Protobuf type {@code QDP_main_frame.user_verification_ans}
   */
  public static final class user_verification_ans extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:QDP_main_frame.user_verification_ans)
      user_verification_ansOrBuilder {
    // Use user_verification_ans.newBuilder() to construct.
    private user_verification_ans(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private user_verification_ans(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final user_verification_ans defaultInstance;
    public static user_verification_ans getDefaultInstance() {
      return defaultInstance;
    }

    public user_verification_ans getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private user_verification_ans(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              QDP_main_frame.QDPMainFrame.other_platform value = QDP_main_frame.QDPMainFrame.other_platform.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                platformType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              jsonAns_ = input.readBytes();
              break;
            }
            case 26: {
              common.Common.errorinfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = error_.toBuilder();
              }
              error_ = input.readMessage(common.Common.errorinfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(error_);
                error_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QDP_main_frame.QDPMainFrame.internal_static_QDP_main_frame_user_verification_ans_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QDP_main_frame.QDPMainFrame.internal_static_QDP_main_frame_user_verification_ans_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QDP_main_frame.QDPMainFrame.user_verification_ans.class, QDP_main_frame.QDPMainFrame.user_verification_ans.Builder.class);
    }

    public static com.google.protobuf.Parser<user_verification_ans> PARSER =
        new com.google.protobuf.AbstractParser<user_verification_ans>() {
      public user_verification_ans parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new user_verification_ans(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<user_verification_ans> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLATFORM_TYPE_FIELD_NUMBER = 1;
    private QDP_main_frame.QDPMainFrame.other_platform platformType_;
    /**
     * <code>optional .QDP_main_frame.other_platform platform_type = 1;</code>
     *
     * <pre>
     *所属平台
     * </pre>
     */
    public boolean hasPlatformType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .QDP_main_frame.other_platform platform_type = 1;</code>
     *
     * <pre>
     *所属平台
     * </pre>
     */
    public QDP_main_frame.QDPMainFrame.other_platform getPlatformType() {
      return platformType_;
    }

    public static final int JSON_ANS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString jsonAns_;
    /**
     * <code>optional bytes json_ans = 2;</code>
     */
    public boolean hasJsonAns() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes json_ans = 2;</code>
     */
    public com.google.protobuf.ByteString getJsonAns() {
      return jsonAns_;
    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private common.Common.errorinfo error_;
    /**
     * <code>optional .common.errorinfo error = 3;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .common.errorinfo error = 3;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    public common.Common.errorinfo getError() {
      return error_;
    }
    /**
     * <code>optional .common.errorinfo error = 3;</code>
     *
     * <pre>
     *错误代码
     * </pre>
     */
    public common.Common.errorinfoOrBuilder getErrorOrBuilder() {
      return error_;
    }

    private void initFields() {
      platformType_ = QDP_main_frame.QDPMainFrame.other_platform.unknown_platform;
      jsonAns_ = com.google.protobuf.ByteString.EMPTY;
      error_ = common.Common.errorinfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, platformType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, jsonAns_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, error_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, platformType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, jsonAns_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, error_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static QDP_main_frame.QDPMainFrame.user_verification_ans parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ans parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ans parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ans parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ans parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ans parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ans parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ans parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ans parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QDP_main_frame.QDPMainFrame.user_verification_ans parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QDP_main_frame.QDPMainFrame.user_verification_ans prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QDP_main_frame.user_verification_ans}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QDP_main_frame.user_verification_ans)
        QDP_main_frame.QDPMainFrame.user_verification_ansOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QDP_main_frame.QDPMainFrame.internal_static_QDP_main_frame_user_verification_ans_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QDP_main_frame.QDPMainFrame.internal_static_QDP_main_frame_user_verification_ans_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QDP_main_frame.QDPMainFrame.user_verification_ans.class, QDP_main_frame.QDPMainFrame.user_verification_ans.Builder.class);
      }

      // Construct using QDP_main_frame.QDPMainFrame.user_verification_ans.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getErrorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        platformType_ = QDP_main_frame.QDPMainFrame.other_platform.unknown_platform;
        bitField0_ = (bitField0_ & ~0x00000001);
        jsonAns_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (errorBuilder_ == null) {
          error_ = common.Common.errorinfo.getDefaultInstance();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QDP_main_frame.QDPMainFrame.internal_static_QDP_main_frame_user_verification_ans_descriptor;
      }

      public QDP_main_frame.QDPMainFrame.user_verification_ans getDefaultInstanceForType() {
        return QDP_main_frame.QDPMainFrame.user_verification_ans.getDefaultInstance();
      }

      public QDP_main_frame.QDPMainFrame.user_verification_ans build() {
        QDP_main_frame.QDPMainFrame.user_verification_ans result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public QDP_main_frame.QDPMainFrame.user_verification_ans buildPartial() {
        QDP_main_frame.QDPMainFrame.user_verification_ans result = new QDP_main_frame.QDPMainFrame.user_verification_ans(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.platformType_ = platformType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jsonAns_ = jsonAns_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QDP_main_frame.QDPMainFrame.user_verification_ans) {
          return mergeFrom((QDP_main_frame.QDPMainFrame.user_verification_ans)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QDP_main_frame.QDPMainFrame.user_verification_ans other) {
        if (other == QDP_main_frame.QDPMainFrame.user_verification_ans.getDefaultInstance()) return this;
        if (other.hasPlatformType()) {
          setPlatformType(other.getPlatformType());
        }
        if (other.hasJsonAns()) {
          setJsonAns(other.getJsonAns());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QDP_main_frame.QDPMainFrame.user_verification_ans parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QDP_main_frame.QDPMainFrame.user_verification_ans) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private QDP_main_frame.QDPMainFrame.other_platform platformType_ = QDP_main_frame.QDPMainFrame.other_platform.unknown_platform;
      /**
       * <code>optional .QDP_main_frame.other_platform platform_type = 1;</code>
       *
       * <pre>
       *所属平台
       * </pre>
       */
      public boolean hasPlatformType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .QDP_main_frame.other_platform platform_type = 1;</code>
       *
       * <pre>
       *所属平台
       * </pre>
       */
      public QDP_main_frame.QDPMainFrame.other_platform getPlatformType() {
        return platformType_;
      }
      /**
       * <code>optional .QDP_main_frame.other_platform platform_type = 1;</code>
       *
       * <pre>
       *所属平台
       * </pre>
       */
      public Builder setPlatformType(QDP_main_frame.QDPMainFrame.other_platform value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        platformType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .QDP_main_frame.other_platform platform_type = 1;</code>
       *
       * <pre>
       *所属平台
       * </pre>
       */
      public Builder clearPlatformType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        platformType_ = QDP_main_frame.QDPMainFrame.other_platform.unknown_platform;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString jsonAns_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes json_ans = 2;</code>
       */
      public boolean hasJsonAns() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes json_ans = 2;</code>
       */
      public com.google.protobuf.ByteString getJsonAns() {
        return jsonAns_;
      }
      /**
       * <code>optional bytes json_ans = 2;</code>
       */
      public Builder setJsonAns(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        jsonAns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes json_ans = 2;</code>
       */
      public Builder clearJsonAns() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jsonAns_ = getDefaultInstance().getJsonAns();
        onChanged();
        return this;
      }

      private common.Common.errorinfo error_ = common.Common.errorinfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.errorinfo, common.Common.errorinfo.Builder, common.Common.errorinfoOrBuilder> errorBuilder_;
      /**
       * <code>optional .common.errorinfo error = 3;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .common.errorinfo error = 3;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public common.Common.errorinfo getError() {
        if (errorBuilder_ == null) {
          return error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .common.errorinfo error = 3;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public Builder setError(common.Common.errorinfo value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 3;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public Builder setError(
          common.Common.errorinfo.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 3;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public Builder mergeError(common.Common.errorinfo value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              error_ != common.Common.errorinfo.getDefaultInstance()) {
            error_ =
              common.Common.errorinfo.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 3;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = common.Common.errorinfo.getDefaultInstance();
          onChanged();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .common.errorinfo error = 3;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public common.Common.errorinfo.Builder getErrorBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.errorinfo error = 3;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      public common.Common.errorinfoOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_;
        }
      }
      /**
       * <code>optional .common.errorinfo error = 3;</code>
       *
       * <pre>
       *错误代码
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.errorinfo, common.Common.errorinfo.Builder, common.Common.errorinfoOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              common.Common.errorinfo, common.Common.errorinfo.Builder, common.Common.errorinfoOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:QDP_main_frame.user_verification_ans)
    }

    static {
      defaultInstance = new user_verification_ans(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:QDP_main_frame.user_verification_ans)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QDP_main_frame_user_verification_ask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QDP_main_frame_user_verification_ask_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QDP_main_frame_user_verification_ans_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QDP_main_frame_user_verification_ans_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024QDP_main_frame.proto\022\016QDP_main_frame\032\024" +
      "QDP_basic_info.proto\032\014common.proto\"\375\001\n\025u" +
      "ser_verification_ask\022-\n\004info\030\001 \001(\0132\037.QDP" +
      "_basic_info.user_basic_info\0225\n\rplatform_" +
      "type\030\002 \001(\0162\036.QDP_main_frame.other_platfo" +
      "rm\022-\n\nask_header\030\003 \001(\0132\031.common.common_a" +
      "sk_header\0228\n\017service_manager\030\004 \001(\0132\037.QDP" +
      "_basic_info.control_service\022\025\n\nquery_typ" +
      "e\030\005 \001(\005:\0010\"\202\001\n\025user_verification_ans\0225\n\r" +
      "platform_type\030\001 \001(\0162\036.QDP_main_frame.oth",
      "er_platform\022\020\n\010json_ans\030\002 \001(\014\022 \n\005error\030\003" +
      " \001(\0132\021.common.errorinfo*`\n\016other_platfor" +
      "m\022\024\n\020unknown_platform\020\000\022\021\n\rCredit_sesame" +
      "\020\001\022\020\n\014fraud_metrix\020\002\022\023\n\017AnRong_Platform\020" +
      "\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          QDP_basic_info.QDPBasicInfo.getDescriptor(),
          common.Common.getDescriptor(),
        }, assigner);
    internal_static_QDP_main_frame_user_verification_ask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QDP_main_frame_user_verification_ask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QDP_main_frame_user_verification_ask_descriptor,
        new java.lang.String[] { "Info", "PlatformType", "AskHeader", "ServiceManager", "QueryType", });
    internal_static_QDP_main_frame_user_verification_ans_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QDP_main_frame_user_verification_ans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QDP_main_frame_user_verification_ans_descriptor,
        new java.lang.String[] { "PlatformType", "JsonAns", "Error", });
    QDP_basic_info.QDPBasicInfo.getDescriptor();
    common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
