// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common_datas.proto

package common_datas;

public final class CommonDatas {
  private CommonDatas() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code common_datas.item_api_type}
   */
  public enum item_api_type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TerminalVersionItems = 1;</code>
     *
     * <pre>
     * 终端版本分布
     * </pre>
     */
    TerminalVersionItems(0, 1),
    ;

    /**
     * <code>TerminalVersionItems = 1;</code>
     *
     * <pre>
     * 终端版本分布
     * </pre>
     */
    public static final int TerminalVersionItems_VALUE = 1;


    public final int getNumber() { return value; }

    public static item_api_type valueOf(int value) {
      switch (value) {
        case 1: return TerminalVersionItems;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<item_api_type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<item_api_type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<item_api_type>() {
            public item_api_type findValueByNumber(int number) {
              return item_api_type.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return common_datas.CommonDatas.getDescriptor().getEnumTypes().get(0);
    }

    private static final item_api_type[] VALUES = values();

    public static item_api_type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private item_api_type(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:common_datas.item_api_type)
  }

  public interface menu_itemsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common_datas.menu_items)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes id = 1;</code>
     *
     * <pre>
     * 编号号
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional bytes id = 1;</code>
     *
     * <pre>
     * 编号号
     * </pre>
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>optional bytes title = 2;</code>
     *
     * <pre>
     * 类型对应的标题
     * </pre>
     */
    boolean hasTitle();
    /**
     * <code>optional bytes title = 2;</code>
     *
     * <pre>
     * 类型对应的标题
     * </pre>
     */
    com.google.protobuf.ByteString getTitle();
  }
  /**
   * Protobuf type {@code common_datas.menu_items}
   *
   * <pre>
   * 通用菜单项
   * </pre>
   */
  public static final class menu_items extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common_datas.menu_items)
      menu_itemsOrBuilder {
    // Use menu_items.newBuilder() to construct.
    private menu_items(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private menu_items(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final menu_items defaultInstance;
    public static menu_items getDefaultInstance() {
      return defaultInstance;
    }

    public menu_items getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private menu_items(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common_datas.CommonDatas.internal_static_common_datas_menu_items_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common_datas.CommonDatas.internal_static_common_datas_menu_items_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              common_datas.CommonDatas.menu_items.class, common_datas.CommonDatas.menu_items.Builder.class);
    }

    public static com.google.protobuf.Parser<menu_items> PARSER =
        new com.google.protobuf.AbstractParser<menu_items>() {
      public menu_items parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new menu_items(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<menu_items> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>optional bytes id = 1;</code>
     *
     * <pre>
     * 编号号
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes id = 1;</code>
     *
     * <pre>
     * 编号号
     * </pre>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString title_;
    /**
     * <code>optional bytes title = 2;</code>
     *
     * <pre>
     * 类型对应的标题
     * </pre>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes title = 2;</code>
     *
     * <pre>
     * 类型对应的标题
     * </pre>
     */
    public com.google.protobuf.ByteString getTitle() {
      return title_;
    }

    private void initFields() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      title_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, title_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, title_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static common_datas.CommonDatas.menu_items parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common_datas.CommonDatas.menu_items parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common_datas.CommonDatas.menu_items parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static common_datas.CommonDatas.menu_items parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static common_datas.CommonDatas.menu_items parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static common_datas.CommonDatas.menu_items parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(common_datas.CommonDatas.menu_items prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common_datas.menu_items}
     *
     * <pre>
     * 通用菜单项
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common_datas.menu_items)
        common_datas.CommonDatas.menu_itemsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return common_datas.CommonDatas.internal_static_common_datas_menu_items_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return common_datas.CommonDatas.internal_static_common_datas_menu_items_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                common_datas.CommonDatas.menu_items.class, common_datas.CommonDatas.menu_items.Builder.class);
      }

      // Construct using common_datas.CommonDatas.menu_items.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return common_datas.CommonDatas.internal_static_common_datas_menu_items_descriptor;
      }

      public common_datas.CommonDatas.menu_items getDefaultInstanceForType() {
        return common_datas.CommonDatas.menu_items.getDefaultInstance();
      }

      public common_datas.CommonDatas.menu_items build() {
        common_datas.CommonDatas.menu_items result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public common_datas.CommonDatas.menu_items buildPartial() {
        common_datas.CommonDatas.menu_items result = new common_datas.CommonDatas.menu_items(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common_datas.CommonDatas.menu_items) {
          return mergeFrom((common_datas.CommonDatas.menu_items)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(common_datas.CommonDatas.menu_items other) {
        if (other == common_datas.CommonDatas.menu_items.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        common_datas.CommonDatas.menu_items parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (common_datas.CommonDatas.menu_items) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes id = 1;</code>
       *
       * <pre>
       * 编号号
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes id = 1;</code>
       *
       * <pre>
       * 编号号
       * </pre>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>optional bytes id = 1;</code>
       *
       * <pre>
       * 编号号
       * </pre>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes id = 1;</code>
       *
       * <pre>
       * 编号号
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString title_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes title = 2;</code>
       *
       * <pre>
       * 类型对应的标题
       * </pre>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes title = 2;</code>
       *
       * <pre>
       * 类型对应的标题
       * </pre>
       */
      public com.google.protobuf.ByteString getTitle() {
        return title_;
      }
      /**
       * <code>optional bytes title = 2;</code>
       *
       * <pre>
       * 类型对应的标题
       * </pre>
       */
      public Builder setTitle(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes title = 2;</code>
       *
       * <pre>
       * 类型对应的标题
       * </pre>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common_datas.menu_items)
    }

    static {
      defaultInstance = new menu_items(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common_datas.menu_items)
  }

  public interface menu_items_askOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common_datas.menu_items_ask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .common_datas.item_api_type enum_type = 1;</code>
     *
     * <pre>
     * 类型枚举
     * </pre>
     */
    boolean hasEnumType();
    /**
     * <code>optional .common_datas.item_api_type enum_type = 1;</code>
     *
     * <pre>
     * 类型枚举
     * </pre>
     */
    common_datas.CommonDatas.item_api_type getEnumType();

    /**
     * <code>optional bytes os_version = 2;</code>
     *
     * <pre>
     * OS类型  0表示所有 1表示安卓  2表示IOS
     * </pre>
     */
    boolean hasOsVersion();
    /**
     * <code>optional bytes os_version = 2;</code>
     *
     * <pre>
     * OS类型  0表示所有 1表示安卓  2表示IOS
     * </pre>
     */
    com.google.protobuf.ByteString getOsVersion();

    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     * 通用的公共请求字段(比如回复的主题)
     * </pre>
     */
    boolean hasAskHeader();
    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     * 通用的公共请求字段(比如回复的主题)
     * </pre>
     */
    common.Common.common_ask_header getAskHeader();
    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     * 通用的公共请求字段(比如回复的主题)
     * </pre>
     */
    common.Common.common_ask_headerOrBuilder getAskHeaderOrBuilder();
  }
  /**
   * Protobuf type {@code common_datas.menu_items_ask}
   */
  public static final class menu_items_ask extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common_datas.menu_items_ask)
      menu_items_askOrBuilder {
    // Use menu_items_ask.newBuilder() to construct.
    private menu_items_ask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private menu_items_ask(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final menu_items_ask defaultInstance;
    public static menu_items_ask getDefaultInstance() {
      return defaultInstance;
    }

    public menu_items_ask getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private menu_items_ask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              common_datas.CommonDatas.item_api_type value = common_datas.CommonDatas.item_api_type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                enumType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              osVersion_ = input.readBytes();
              break;
            }
            case 26: {
              common.Common.common_ask_header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = askHeader_.toBuilder();
              }
              askHeader_ = input.readMessage(common.Common.common_ask_header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(askHeader_);
                askHeader_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common_datas.CommonDatas.internal_static_common_datas_menu_items_ask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common_datas.CommonDatas.internal_static_common_datas_menu_items_ask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              common_datas.CommonDatas.menu_items_ask.class, common_datas.CommonDatas.menu_items_ask.Builder.class);
    }

    public static com.google.protobuf.Parser<menu_items_ask> PARSER =
        new com.google.protobuf.AbstractParser<menu_items_ask>() {
      public menu_items_ask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new menu_items_ask(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<menu_items_ask> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENUM_TYPE_FIELD_NUMBER = 1;
    private common_datas.CommonDatas.item_api_type enumType_;
    /**
     * <code>optional .common_datas.item_api_type enum_type = 1;</code>
     *
     * <pre>
     * 类型枚举
     * </pre>
     */
    public boolean hasEnumType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .common_datas.item_api_type enum_type = 1;</code>
     *
     * <pre>
     * 类型枚举
     * </pre>
     */
    public common_datas.CommonDatas.item_api_type getEnumType() {
      return enumType_;
    }

    public static final int OS_VERSION_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString osVersion_;
    /**
     * <code>optional bytes os_version = 2;</code>
     *
     * <pre>
     * OS类型  0表示所有 1表示安卓  2表示IOS
     * </pre>
     */
    public boolean hasOsVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes os_version = 2;</code>
     *
     * <pre>
     * OS类型  0表示所有 1表示安卓  2表示IOS
     * </pre>
     */
    public com.google.protobuf.ByteString getOsVersion() {
      return osVersion_;
    }

    public static final int ASK_HEADER_FIELD_NUMBER = 3;
    private common.Common.common_ask_header askHeader_;
    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     * 通用的公共请求字段(比如回复的主题)
     * </pre>
     */
    public boolean hasAskHeader() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     * 通用的公共请求字段(比如回复的主题)
     * </pre>
     */
    public common.Common.common_ask_header getAskHeader() {
      return askHeader_;
    }
    /**
     * <code>optional .common.common_ask_header ask_header = 3;</code>
     *
     * <pre>
     * 通用的公共请求字段(比如回复的主题)
     * </pre>
     */
    public common.Common.common_ask_headerOrBuilder getAskHeaderOrBuilder() {
      return askHeader_;
    }

    private void initFields() {
      enumType_ = common_datas.CommonDatas.item_api_type.TerminalVersionItems;
      osVersion_ = com.google.protobuf.ByteString.EMPTY;
      askHeader_ = common.Common.common_ask_header.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, enumType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, osVersion_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, askHeader_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, enumType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, osVersion_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, askHeader_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static common_datas.CommonDatas.menu_items_ask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common_datas.CommonDatas.menu_items_ask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items_ask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common_datas.CommonDatas.menu_items_ask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items_ask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static common_datas.CommonDatas.menu_items_ask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items_ask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static common_datas.CommonDatas.menu_items_ask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items_ask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static common_datas.CommonDatas.menu_items_ask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(common_datas.CommonDatas.menu_items_ask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common_datas.menu_items_ask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common_datas.menu_items_ask)
        common_datas.CommonDatas.menu_items_askOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return common_datas.CommonDatas.internal_static_common_datas_menu_items_ask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return common_datas.CommonDatas.internal_static_common_datas_menu_items_ask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                common_datas.CommonDatas.menu_items_ask.class, common_datas.CommonDatas.menu_items_ask.Builder.class);
      }

      // Construct using common_datas.CommonDatas.menu_items_ask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAskHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        enumType_ = common_datas.CommonDatas.item_api_type.TerminalVersionItems;
        bitField0_ = (bitField0_ & ~0x00000001);
        osVersion_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (askHeaderBuilder_ == null) {
          askHeader_ = common.Common.common_ask_header.getDefaultInstance();
        } else {
          askHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return common_datas.CommonDatas.internal_static_common_datas_menu_items_ask_descriptor;
      }

      public common_datas.CommonDatas.menu_items_ask getDefaultInstanceForType() {
        return common_datas.CommonDatas.menu_items_ask.getDefaultInstance();
      }

      public common_datas.CommonDatas.menu_items_ask build() {
        common_datas.CommonDatas.menu_items_ask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public common_datas.CommonDatas.menu_items_ask buildPartial() {
        common_datas.CommonDatas.menu_items_ask result = new common_datas.CommonDatas.menu_items_ask(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.enumType_ = enumType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.osVersion_ = osVersion_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (askHeaderBuilder_ == null) {
          result.askHeader_ = askHeader_;
        } else {
          result.askHeader_ = askHeaderBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common_datas.CommonDatas.menu_items_ask) {
          return mergeFrom((common_datas.CommonDatas.menu_items_ask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(common_datas.CommonDatas.menu_items_ask other) {
        if (other == common_datas.CommonDatas.menu_items_ask.getDefaultInstance()) return this;
        if (other.hasEnumType()) {
          setEnumType(other.getEnumType());
        }
        if (other.hasOsVersion()) {
          setOsVersion(other.getOsVersion());
        }
        if (other.hasAskHeader()) {
          mergeAskHeader(other.getAskHeader());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        common_datas.CommonDatas.menu_items_ask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (common_datas.CommonDatas.menu_items_ask) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private common_datas.CommonDatas.item_api_type enumType_ = common_datas.CommonDatas.item_api_type.TerminalVersionItems;
      /**
       * <code>optional .common_datas.item_api_type enum_type = 1;</code>
       *
       * <pre>
       * 类型枚举
       * </pre>
       */
      public boolean hasEnumType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .common_datas.item_api_type enum_type = 1;</code>
       *
       * <pre>
       * 类型枚举
       * </pre>
       */
      public common_datas.CommonDatas.item_api_type getEnumType() {
        return enumType_;
      }
      /**
       * <code>optional .common_datas.item_api_type enum_type = 1;</code>
       *
       * <pre>
       * 类型枚举
       * </pre>
       */
      public Builder setEnumType(common_datas.CommonDatas.item_api_type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        enumType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .common_datas.item_api_type enum_type = 1;</code>
       *
       * <pre>
       * 类型枚举
       * </pre>
       */
      public Builder clearEnumType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        enumType_ = common_datas.CommonDatas.item_api_type.TerminalVersionItems;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString osVersion_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes os_version = 2;</code>
       *
       * <pre>
       * OS类型  0表示所有 1表示安卓  2表示IOS
       * </pre>
       */
      public boolean hasOsVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes os_version = 2;</code>
       *
       * <pre>
       * OS类型  0表示所有 1表示安卓  2表示IOS
       * </pre>
       */
      public com.google.protobuf.ByteString getOsVersion() {
        return osVersion_;
      }
      /**
       * <code>optional bytes os_version = 2;</code>
       *
       * <pre>
       * OS类型  0表示所有 1表示安卓  2表示IOS
       * </pre>
       */
      public Builder setOsVersion(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        osVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes os_version = 2;</code>
       *
       * <pre>
       * OS类型  0表示所有 1表示安卓  2表示IOS
       * </pre>
       */
      public Builder clearOsVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        osVersion_ = getDefaultInstance().getOsVersion();
        onChanged();
        return this;
      }

      private common.Common.common_ask_header askHeader_ = common.Common.common_ask_header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.common_ask_header, common.Common.common_ask_header.Builder, common.Common.common_ask_headerOrBuilder> askHeaderBuilder_;
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       * 通用的公共请求字段(比如回复的主题)
       * </pre>
       */
      public boolean hasAskHeader() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       * 通用的公共请求字段(比如回复的主题)
       * </pre>
       */
      public common.Common.common_ask_header getAskHeader() {
        if (askHeaderBuilder_ == null) {
          return askHeader_;
        } else {
          return askHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       * 通用的公共请求字段(比如回复的主题)
       * </pre>
       */
      public Builder setAskHeader(common.Common.common_ask_header value) {
        if (askHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          askHeader_ = value;
          onChanged();
        } else {
          askHeaderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       * 通用的公共请求字段(比如回复的主题)
       * </pre>
       */
      public Builder setAskHeader(
          common.Common.common_ask_header.Builder builderForValue) {
        if (askHeaderBuilder_ == null) {
          askHeader_ = builderForValue.build();
          onChanged();
        } else {
          askHeaderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       * 通用的公共请求字段(比如回复的主题)
       * </pre>
       */
      public Builder mergeAskHeader(common.Common.common_ask_header value) {
        if (askHeaderBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              askHeader_ != common.Common.common_ask_header.getDefaultInstance()) {
            askHeader_ =
              common.Common.common_ask_header.newBuilder(askHeader_).mergeFrom(value).buildPartial();
          } else {
            askHeader_ = value;
          }
          onChanged();
        } else {
          askHeaderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       * 通用的公共请求字段(比如回复的主题)
       * </pre>
       */
      public Builder clearAskHeader() {
        if (askHeaderBuilder_ == null) {
          askHeader_ = common.Common.common_ask_header.getDefaultInstance();
          onChanged();
        } else {
          askHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       * 通用的公共请求字段(比如回复的主题)
       * </pre>
       */
      public common.Common.common_ask_header.Builder getAskHeaderBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAskHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       * 通用的公共请求字段(比如回复的主题)
       * </pre>
       */
      public common.Common.common_ask_headerOrBuilder getAskHeaderOrBuilder() {
        if (askHeaderBuilder_ != null) {
          return askHeaderBuilder_.getMessageOrBuilder();
        } else {
          return askHeader_;
        }
      }
      /**
       * <code>optional .common.common_ask_header ask_header = 3;</code>
       *
       * <pre>
       * 通用的公共请求字段(比如回复的主题)
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.common_ask_header, common.Common.common_ask_header.Builder, common.Common.common_ask_headerOrBuilder> 
          getAskHeaderFieldBuilder() {
        if (askHeaderBuilder_ == null) {
          askHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              common.Common.common_ask_header, common.Common.common_ask_header.Builder, common.Common.common_ask_headerOrBuilder>(
                  getAskHeader(),
                  getParentForChildren(),
                  isClean());
          askHeader_ = null;
        }
        return askHeaderBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:common_datas.menu_items_ask)
    }

    static {
      defaultInstance = new menu_items_ask(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common_datas.menu_items_ask)
  }

  public interface menu_items_ansOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common_datas.menu_items_ans)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .common_datas.menu_items item = 1;</code>
     *
     * <pre>
     *历史资金流水类型
     * </pre>
     */
    java.util.List<common_datas.CommonDatas.menu_items> 
        getItemList();
    /**
     * <code>repeated .common_datas.menu_items item = 1;</code>
     *
     * <pre>
     *历史资金流水类型
     * </pre>
     */
    common_datas.CommonDatas.menu_items getItem(int index);
    /**
     * <code>repeated .common_datas.menu_items item = 1;</code>
     *
     * <pre>
     *历史资金流水类型
     * </pre>
     */
    int getItemCount();
    /**
     * <code>repeated .common_datas.menu_items item = 1;</code>
     *
     * <pre>
     *历史资金流水类型
     * </pre>
     */
    java.util.List<? extends common_datas.CommonDatas.menu_itemsOrBuilder> 
        getItemOrBuilderList();
    /**
     * <code>repeated .common_datas.menu_items item = 1;</code>
     *
     * <pre>
     *历史资金流水类型
     * </pre>
     */
    common_datas.CommonDatas.menu_itemsOrBuilder getItemOrBuilder(
        int index);

    /**
     * <code>optional .common.result_info result = 2;</code>
     *
     * <pre>
     * 错误代码
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional .common.result_info result = 2;</code>
     *
     * <pre>
     * 错误代码
     * </pre>
     */
    common.Common.result_info getResult();
    /**
     * <code>optional .common.result_info result = 2;</code>
     *
     * <pre>
     * 错误代码
     * </pre>
     */
    common.Common.result_infoOrBuilder getResultOrBuilder();
  }
  /**
   * Protobuf type {@code common_datas.menu_items_ans}
   */
  public static final class menu_items_ans extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common_datas.menu_items_ans)
      menu_items_ansOrBuilder {
    // Use menu_items_ans.newBuilder() to construct.
    private menu_items_ans(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private menu_items_ans(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final menu_items_ans defaultInstance;
    public static menu_items_ans getDefaultInstance() {
      return defaultInstance;
    }

    public menu_items_ans getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private menu_items_ans(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                item_ = new java.util.ArrayList<common_datas.CommonDatas.menu_items>();
                mutable_bitField0_ |= 0x00000001;
              }
              item_.add(input.readMessage(common_datas.CommonDatas.menu_items.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              common.Common.result_info.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(common.Common.result_info.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          item_ = java.util.Collections.unmodifiableList(item_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common_datas.CommonDatas.internal_static_common_datas_menu_items_ans_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common_datas.CommonDatas.internal_static_common_datas_menu_items_ans_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              common_datas.CommonDatas.menu_items_ans.class, common_datas.CommonDatas.menu_items_ans.Builder.class);
    }

    public static com.google.protobuf.Parser<menu_items_ans> PARSER =
        new com.google.protobuf.AbstractParser<menu_items_ans>() {
      public menu_items_ans parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new menu_items_ans(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<menu_items_ans> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ITEM_FIELD_NUMBER = 1;
    private java.util.List<common_datas.CommonDatas.menu_items> item_;
    /**
     * <code>repeated .common_datas.menu_items item = 1;</code>
     *
     * <pre>
     *历史资金流水类型
     * </pre>
     */
    public java.util.List<common_datas.CommonDatas.menu_items> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .common_datas.menu_items item = 1;</code>
     *
     * <pre>
     *历史资金流水类型
     * </pre>
     */
    public java.util.List<? extends common_datas.CommonDatas.menu_itemsOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .common_datas.menu_items item = 1;</code>
     *
     * <pre>
     *历史资金流水类型
     * </pre>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .common_datas.menu_items item = 1;</code>
     *
     * <pre>
     *历史资金流水类型
     * </pre>
     */
    public common_datas.CommonDatas.menu_items getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .common_datas.menu_items item = 1;</code>
     *
     * <pre>
     *历史资金流水类型
     * </pre>
     */
    public common_datas.CommonDatas.menu_itemsOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private common.Common.result_info result_;
    /**
     * <code>optional .common.result_info result = 2;</code>
     *
     * <pre>
     * 错误代码
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .common.result_info result = 2;</code>
     *
     * <pre>
     * 错误代码
     * </pre>
     */
    public common.Common.result_info getResult() {
      return result_;
    }
    /**
     * <code>optional .common.result_info result = 2;</code>
     *
     * <pre>
     * 错误代码
     * </pre>
     */
    public common.Common.result_infoOrBuilder getResultOrBuilder() {
      return result_;
    }

    private void initFields() {
      item_ = java.util.Collections.emptyList();
      result_ = common.Common.result_info.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(1, item_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, item_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static common_datas.CommonDatas.menu_items_ans parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common_datas.CommonDatas.menu_items_ans parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items_ans parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common_datas.CommonDatas.menu_items_ans parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items_ans parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static common_datas.CommonDatas.menu_items_ans parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items_ans parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static common_datas.CommonDatas.menu_items_ans parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static common_datas.CommonDatas.menu_items_ans parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static common_datas.CommonDatas.menu_items_ans parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(common_datas.CommonDatas.menu_items_ans prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common_datas.menu_items_ans}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common_datas.menu_items_ans)
        common_datas.CommonDatas.menu_items_ansOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return common_datas.CommonDatas.internal_static_common_datas_menu_items_ans_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return common_datas.CommonDatas.internal_static_common_datas_menu_items_ans_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                common_datas.CommonDatas.menu_items_ans.class, common_datas.CommonDatas.menu_items_ans.Builder.class);
      }

      // Construct using common_datas.CommonDatas.menu_items_ans.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemBuilder_.clear();
        }
        if (resultBuilder_ == null) {
          result_ = common.Common.result_info.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return common_datas.CommonDatas.internal_static_common_datas_menu_items_ans_descriptor;
      }

      public common_datas.CommonDatas.menu_items_ans getDefaultInstanceForType() {
        return common_datas.CommonDatas.menu_items_ans.getDefaultInstance();
      }

      public common_datas.CommonDatas.menu_items_ans build() {
        common_datas.CommonDatas.menu_items_ans result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public common_datas.CommonDatas.menu_items_ans buildPartial() {
        common_datas.CommonDatas.menu_items_ans result = new common_datas.CommonDatas.menu_items_ans(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common_datas.CommonDatas.menu_items_ans) {
          return mergeFrom((common_datas.CommonDatas.menu_items_ans)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(common_datas.CommonDatas.menu_items_ans other) {
        if (other == common_datas.CommonDatas.menu_items_ans.getDefaultInstance()) return this;
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        common_datas.CommonDatas.menu_items_ans parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (common_datas.CommonDatas.menu_items_ans) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<common_datas.CommonDatas.menu_items> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          item_ = new java.util.ArrayList<common_datas.CommonDatas.menu_items>(item_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          common_datas.CommonDatas.menu_items, common_datas.CommonDatas.menu_items.Builder, common_datas.CommonDatas.menu_itemsOrBuilder> itemBuilder_;

      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public java.util.List<common_datas.CommonDatas.menu_items> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public common_datas.CommonDatas.menu_items getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public Builder setItem(
          int index, common_datas.CommonDatas.menu_items value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public Builder setItem(
          int index, common_datas.CommonDatas.menu_items.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public Builder addItem(common_datas.CommonDatas.menu_items value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public Builder addItem(
          int index, common_datas.CommonDatas.menu_items value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public Builder addItem(
          common_datas.CommonDatas.menu_items.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public Builder addItem(
          int index, common_datas.CommonDatas.menu_items.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends common_datas.CommonDatas.menu_items> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public common_datas.CommonDatas.menu_items.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public common_datas.CommonDatas.menu_itemsOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public java.util.List<? extends common_datas.CommonDatas.menu_itemsOrBuilder> 
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public common_datas.CommonDatas.menu_items.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            common_datas.CommonDatas.menu_items.getDefaultInstance());
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public common_datas.CommonDatas.menu_items.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, common_datas.CommonDatas.menu_items.getDefaultInstance());
      }
      /**
       * <code>repeated .common_datas.menu_items item = 1;</code>
       *
       * <pre>
       *历史资金流水类型
       * </pre>
       */
      public java.util.List<common_datas.CommonDatas.menu_items.Builder> 
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          common_datas.CommonDatas.menu_items, common_datas.CommonDatas.menu_items.Builder, common_datas.CommonDatas.menu_itemsOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              common_datas.CommonDatas.menu_items, common_datas.CommonDatas.menu_items.Builder, common_datas.CommonDatas.menu_itemsOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      private common.Common.result_info result_ = common.Common.result_info.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.result_info, common.Common.result_info.Builder, common.Common.result_infoOrBuilder> resultBuilder_;
      /**
       * <code>optional .common.result_info result = 2;</code>
       *
       * <pre>
       * 错误代码
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .common.result_info result = 2;</code>
       *
       * <pre>
       * 错误代码
       * </pre>
       */
      public common.Common.result_info getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .common.result_info result = 2;</code>
       *
       * <pre>
       * 错误代码
       * </pre>
       */
      public Builder setResult(common.Common.result_info value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.result_info result = 2;</code>
       *
       * <pre>
       * 错误代码
       * </pre>
       */
      public Builder setResult(
          common.Common.result_info.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.result_info result = 2;</code>
       *
       * <pre>
       * 错误代码
       * </pre>
       */
      public Builder mergeResult(common.Common.result_info value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              result_ != common.Common.result_info.getDefaultInstance()) {
            result_ =
              common.Common.result_info.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.result_info result = 2;</code>
       *
       * <pre>
       * 错误代码
       * </pre>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = common.Common.result_info.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .common.result_info result = 2;</code>
       *
       * <pre>
       * 错误代码
       * </pre>
       */
      public common.Common.result_info.Builder getResultBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.result_info result = 2;</code>
       *
       * <pre>
       * 错误代码
       * </pre>
       */
      public common.Common.result_infoOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>optional .common.result_info result = 2;</code>
       *
       * <pre>
       * 错误代码
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          common.Common.result_info, common.Common.result_info.Builder, common.Common.result_infoOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              common.Common.result_info, common.Common.result_info.Builder, common.Common.result_infoOrBuilder>(
                  getResult(),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:common_datas.menu_items_ans)
    }

    static {
      defaultInstance = new menu_items_ans(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common_datas.menu_items_ans)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_datas_menu_items_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_datas_menu_items_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_datas_menu_items_ask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_datas_menu_items_ask_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_datas_menu_items_ans_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_datas_menu_items_ans_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022common_datas.proto\022\014common_datas\032\014comm" +
      "on.proto\"\'\n\nmenu_items\022\n\n\002id\030\001 \001(\014\022\r\n\005ti" +
      "tle\030\002 \001(\014\"\203\001\n\016menu_items_ask\022.\n\tenum_typ" +
      "e\030\001 \001(\0162\033.common_datas.item_api_type\022\022\n\n" +
      "os_version\030\002 \001(\014\022-\n\nask_header\030\003 \001(\0132\031.c" +
      "ommon.common_ask_header\"]\n\016menu_items_an" +
      "s\022&\n\004item\030\001 \003(\0132\030.common_datas.menu_item" +
      "s\022#\n\006result\030\002 \001(\0132\023.common.result_info*)" +
      "\n\ritem_api_type\022\030\n\024TerminalVersionItems\020" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          common.Common.getDescriptor(),
        }, assigner);
    internal_static_common_datas_menu_items_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_datas_menu_items_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_datas_menu_items_descriptor,
        new java.lang.String[] { "Id", "Title", });
    internal_static_common_datas_menu_items_ask_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_datas_menu_items_ask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_datas_menu_items_ask_descriptor,
        new java.lang.String[] { "EnumType", "OsVersion", "AskHeader", });
    internal_static_common_datas_menu_items_ans_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_common_datas_menu_items_ans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_datas_menu_items_ans_descriptor,
        new java.lang.String[] { "Item", "Result", });
    common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
